# Práctico Limpieza de Datos con Pandas - Clínica Veterinaria

**Contexto:** Una clínica veterinaria registró información de mascotas atendidas durante distintas semanas. El dataset contiene inconsistencias, valores faltantes y datos incorrectos.

In [172]:
import pandas as pd
import numpy as np

## Creación del Dataset

In [173]:
mascotas = pd.DataFrame({
    "ID_Consulta": [201, 202, 203, 204, 204, 206, 207, 208, 209, 210],
    "NombreMascota": [
        "Luna", "Max", "Milo", "Nina", "Nina",
        None, "Rocky", "Simba", "Mora", "Luna"
    ],
    "Especie": [
        "Perro", "gato", "GATO", "Perro",
        "Perro", "Conejo", "conejo", "Perro", None, "PERRO"
    ],
    "PesoKg": [
        "12.5", "4.2", "error", "8.1", "8.1",
        "2.4", None, "15", "-3", "13"
    ],
    "Edad": [
        5, 3, np.nan, 2, 2, 1, 4, -1, 6, 5
    ],
    "FechaConsulta": [
        "01/04/2025", "2025-04-02", "03-04-2025", "04/04/2025",
        "04/04/2025", "05/04/2025", "06/04/2025", "07/04/2025",
        "08/04/2025", "09/04/2025"
    ]
})

mascotas

   ID_Consulta NombreMascota Especie PesoKg  Edad FechaConsulta
0          201          Luna   Perro   12.5   5.0    01/04/2025
1          202           Max    gato    4.2   3.0    2025-04-02
2          203          Milo    GATO  error   NaN    03-04-2025
3          204          Nina   Perro    8.1   2.0    04/04/2025
4          204          Nina   Perro    8.1   2.0    04/04/2025
5          206           NaN  Conejo    2.4   1.0    05/04/2025
6          207         Rocky  conejo    NaN   4.0    06/04/2025
7          208         Simba   Perro     15  -1.0    07/04/2025
8          209          Mora     NaN     -3   6.0    08/04/2025
9          210          Luna   PERRO     13   5.0    09/04/2025

---
## Actividad 1: Mostrar las primeras filas del DataFrame

In [174]:
mascotas.head()

   ID_Consulta NombreMascota Especie PesoKg  Edad FechaConsulta
0          201          Luna   Perro   12.5   5.0    01/04/2025
1          202           Max    gato    4.2   3.0    2025-04-02
2          203          Milo    GATO  error   NaN    03-04-2025
3          204          Nina   Perro    8.1   2.0    04/04/2025
4          204          Nina   Perro    8.1   2.0    04/04/2025

---
## Actividad 2: Obtener información general

In [175]:
mascotas.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_Consulta    10 non-null     int64
 1   NombreMascota  9 non-null      str
 2   Especie        9 non-null      str
 3   PesoKg         9 non-null      str
 4   Edad           9 non-null      float64
 5   FechaConsulta  10 non-null     str
dtypes: float64(1), int64(1), str(4)
memory usage: 612.0 bytes

---
## Actividad 3: Mostrar estadísticas descriptivas

In [176]:
mascotas.describe()

       ID_Consulta      Edad
count    10.000000  9.000000
mean    205.400000  3.000000
std       3.062316  2.236068
min     201.000000 -1.000000
25%     203.250000  2.000000
50%     205.000000  3.000000
75%     207.750000  5.000000
max     210.000000  6.000000

In [177]:
# Estadísticas de columnas de texto (object)
mascotas.describe(include="object")

C:\Users\Personal\AppData\Local\Temp\ipykernel_11828\1804387101.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  mascotas.describe(include="object")

       NombreMascota Especie PesoKg FechaConsulta
count              9       9      9            10
unique             7       6      8             9
top             Luna   Perro    8.1    04/04/2025
freq               2       4      2             2

---
## Actividad 4: Identificar valores faltantes, duplicados y tipos incorrectos

In [178]:
# Conteo y porcentaje de nulos por columna
nulos = mascotas.isnull().sum()
porcentaje = (nulos / len(mascotas) * 100).round(1)

resumen_nulos = pd.DataFrame({
    "Nulos": nulos,
    "Porcentaje (%)": porcentaje
})

print("=== VALORES FALTANTES ===")
print(resumen_nulos)
print()

=== VALORES FALTANTES ===
               Nulos  Porcentaje (%)
ID_Consulta        0             0.0
NombreMascota      1            10.0
Especie            1            10.0
PesoKg             1            10.0
Edad               1            10.0
FechaConsulta      0             0.0

In [179]:
# Duplicados
print(f"=== DUPLICADOS ===")
print(f"Filas duplicadas exactas: {mascotas.duplicated().sum()}")
print()
print("Filas duplicadas:")
print(mascotas[mascotas.duplicated(keep=False)])

=== DUPLICADOS ===
Filas duplicadas exactas: 1

Filas duplicadas:
   ID_Consulta NombreMascota Especie PesoKg  Edad FechaConsulta
3          204          Nina   Perro    8.1   2.0    04/04/2025
4          204          Nina   Perro    8.1   2.0    04/04/2025

In [180]:
# Tipos de datos
print("=== TIPOS DE DATOS ===")
print(mascotas.dtypes)
print()
print("Observaciones:")
print("- PesoKg es 'object' (texto) en lugar de numérico")
print("- FechaConsulta es 'object' en lugar de datetime")

=== TIPOS DE DATOS ===
ID_Consulta        int64
NombreMascota        str
Especie              str
PesoKg               str
Edad             float64
FechaConsulta        str
dtype: object

Observaciones:
- PesoKg es 'object' (texto) en lugar de numérico
- FechaConsulta es 'object' en lugar de datetime

In [181]:
# Frecuencia de valores en Especie para ver inconsistencias
print("Especies:")
print(mascotas["Especie"].value_counts(dropna=False))

Especies:
Especie
Perro     4
gato      1
GATO      1
Conejo    1
conejo    1
NaN       1
PERRO     1
Name: count, dtype: int64

---
## Actividad 7: Unificar formatos de texto en la columna Especie

Siguiendo el paso 2 del cuaderno de clase: normalizar cadenas de texto con `str.strip()` y `str.capitalize()`.

In [182]:
# Trabajamos sobre una copia
df_limpio = mascotas.copy()

# Normalizar Especie: eliminar espacios y capitalizar
df_limpio["Especie"] = df_limpio["Especie"].str.strip().str.capitalize()

print("Especies únicas después de limpiar:")
print(df_limpio["Especie"].value_counts(dropna=False))

Especies únicas después de limpiar:
Especie
Perro     5
Gato      2
Conejo    2
NaN       1
Name: count, dtype: int64

---
## Actividad 5: Detectar y reemplazar valores nulos

Siguiendo la estrategia de clase:
- Variables categóricas → imputar con **moda**
- Variables numéricas → imputar con **media** o **mediana**

In [183]:
# Nulos actuales después de la limpieza de texto
print("Nulos actuales:")
print(df_limpio.isnull().sum())
print()

Nulos actuales:
ID_Consulta      0
NombreMascota    1
Especie          1
PesoKg           1
Edad             1
FechaConsulta    0
dtype: int64

In [184]:
# NombreMascota (categórica) → imputar con moda
moda_nombre = df_limpio["NombreMascota"].mode()[0]
df_limpio["NombreMascota"] = df_limpio["NombreMascota"].fillna(moda_nombre)
print(f"NombreMascota imputada con moda: '{moda_nombre}'")

NombreMascota imputada con moda: 'Luna'

In [185]:
# Especie (categórica) → imputar con moda
moda_especie = df_limpio["Especie"].mode()[0]
df_limpio["Especie"] = df_limpio["Especie"].fillna(moda_especie)
print(f"Especie imputada con moda: '{moda_especie}'")

Especie imputada con moda: 'Perro'

In [186]:
# Edad (numérica) → imputar con mediana (más robusta ante outliers, como se vio en clase)
mediana_edad = df_limpio["Edad"].median()
df_limpio["Edad"] = df_limpio["Edad"].fillna(mediana_edad)
print(f"Edad imputada con mediana: {mediana_edad}")

Edad imputada con mediana: 3.0

In [187]:
# Verificamos que no queden nulos (PesoKg se trata en la actividad 8)
print("Nulos restantes:")
print(df_limpio.isnull().sum())

Nulos restantes:
ID_Consulta      0
NombreMascota    0
Especie          0
PesoKg           1
Edad             0
FechaConsulta    0
dtype: int64

---
## Actividad 6: Eliminar registros duplicados

Usando `drop_duplicates(keep='first')` como se vio en clase.

In [188]:
print(f"Filas antes de eliminar duplicados: {len(df_limpio)}")

# Eliminar duplicados exactos en todas las columnas
df_limpio = df_limpio.drop_duplicates(keep="first")
print(f"Filas después de eliminar duplicados exactos: {len(df_limpio)}")

# Resetear el índice después de eliminar filas
df_limpio.reset_index(drop=True, inplace=True)
print("Índice del DataFrame reseteado.")

Filas antes de eliminar duplicados: 10
Filas después de eliminar duplicados exactos: 9
Índice del DataFrame reseteado.

---
## Actividad 8: Convertir PesoKg a tipo numérico

Usando `pd.to_numeric(errors='coerce')` como se vio en clase. Los valores no convertibles (como 'error') se transforman en NaN.

In [189]:
print("Antes - tipo de dato PesoKg:", df_limpio["PesoKg"].dtype)
print("Valores actuales:")
print(df_limpio["PesoKg"].values)
print()

Antes - tipo de dato PesoKg: str
Valores actuales:
<StringArray>
['12.5', '4.2', 'error', '8.1', '2.4', nan, '15', '-3', '13']
Length: 9, dtype: str

In [190]:
# Convertir a numérico (errors='coerce' convierte 'error' y similares a NaN)
df_limpio["PesoKg"] = pd.to_numeric(df_limpio["PesoKg"], errors="coerce")

print("Después - tipo de dato PesoKg:", df_limpio["PesoKg"].dtype)
print(df_limpio["PesoKg"])

Después - tipo de dato PesoKg: float64
0    12.5
1     4.2
2     NaN
3     8.1
4     2.4
5     NaN
6    15.0
7    -3.0
8    13.0
Name: PesoKg, dtype: float64

In [191]:
# Imputar los NaN generados en PesoKg con la mediana
mediana_peso = df_limpio["PesoKg"].median()
df_limpio["PesoKg"] = df_limpio["PesoKg"].fillna(mediana_peso)
print(f"PesoKg: NaN imputados con mediana: {mediana_peso}")

PesoKg: NaN imputados con mediana: 8.1

---
## Actividad 9: Convertir FechaConsulta a datetime

Usando `pd.to_datetime(dayfirst=True, format='mixed')` como se vio en clase para manejar distintos formatos de fecha.

In [192]:
print("Antes - tipo de dato FechaConsulta:", df_limpio["FechaConsulta"].dtype)
print("Valores únicos:", df_limpio["FechaConsulta"].unique())

Antes - tipo de dato FechaConsulta: str
Valores únicos: <StringArray>
['01/04/2025', '2025-04-02', '03-04-2025', '04/04/2025', '05/04/2025',
 '06/04/2025', '07/04/2025', '08/04/2025', '09/04/2025']
Length: 9, dtype: str

In [193]:
# Convertir a datetime (dayfirst=True y format='mixed' para manejar distintos formatos)
df_limpio["FechaConsulta"] = pd.to_datetime(df_limpio["FechaConsulta"], dayfirst=True, format='mixed')

print("Después - tipo de dato:", df_limpio["FechaConsulta"].dtype)
print(df_limpio["FechaConsulta"])

Después - tipo de dato: datetime64[us]
0   2025-04-01
1   2025-02-04
2   2025-04-03
3   2025-04-04
4   2025-04-05
5   2025-04-06
6   2025-04-07
7   2025-04-08
8   2025-04-09
Name: FechaConsulta, dtype: datetime64[us]

---
## Actividad 10: Detectar y corregir valores inválidos

Siguiendo el paso 5 de clase (Identificación de Valores Sospechosos): usamos `describe()` para inspeccionar rangos y detectar valores fuera de lugar. Luego usamos máscaras booleanas para reemplazar por la mediana.

In [194]:
# Inspeccionar rangos con describe()
print("=== Estadísticas para detectar valores sospechosos ===")
print(df_limpio[["PesoKg", "Edad"]].describe())

=== Estadísticas para detectar valores sospechosos ===
          PesoKg      Edad
count   9.000000  9.000000
mean    7.600000  3.111111
std     5.696929  2.204793
min    -3.000000 -1.000000
25%     4.200000  2.000000
50%     8.100000  3.000000
75%    12.500000  5.000000
max    15.000000  6.000000

In [195]:
# PesoKg: valores negativos son inválidos
print("Valores de PesoKg negativos:")
print(df_limpio[df_limpio["PesoKg"] < 0])
print()

# Reemplazar valores negativos de PesoKg por la mediana (máscara booleana)
mediana_peso = df_limpio.loc[df_limpio["PesoKg"] > 0, "PesoKg"].median()
df_limpio.loc[df_limpio["PesoKg"] < 0, "PesoKg"] = mediana_peso
print(f"PesoKg negativos reemplazados por mediana: {mediana_peso}")

Valores de PesoKg negativos:
   ID_Consulta NombreMascota Especie  PesoKg  Edad FechaConsulta
7          209          Mora   Perro    -3.0   6.0    2025-04-08

PesoKg negativos reemplazados por mediana: 8.1

In [196]:
# Edad: valores negativos son inválidos
print("Valores de Edad negativos:")
print(df_limpio[df_limpio["Edad"] < 0])
print()

# Reemplazar valores negativos de Edad por la mediana (máscara booleana)
mediana_edad = df_limpio.loc[df_limpio["Edad"] > 0, "Edad"].median()
df_limpio.loc[df_limpio["Edad"] < 0, "Edad"] = mediana_edad
print(f"Edad negativos reemplazados por mediana: {mediana_edad}")

Valores de Edad negativos:
   ID_Consulta NombreMascota Especie  PesoKg  Edad FechaConsulta
6          208         Simba   Perro    15.0  -1.0    2025-04-07

Edad negativos reemplazados por mediana: 3.5

---
## Validación Final

Como se vio en clase (Paso 7), hacemos una revisión final para confirmar que el dataset quedó limpio.

In [197]:
print("=== RESULTADOS ===")
print(f"Filas originales : {len(mascotas)}")
print(f"Filas limpias    : {len(df_limpio)}")
print(f"\nNulos restantes  : {df_limpio.isnull().sum().sum()}")
print(f"Duplicados rest. : {df_limpio.duplicated().sum()}")
print(f"\nTipos de datos:")
print(df_limpio.dtypes)

=== RESULTADOS ===
Filas originales : 10
Filas limpias    : 9

Nulos restantes  : 0
Duplicados rest. : 0

Tipos de datos:
ID_Consulta               int64
NombreMascota               str
Especie                     str
PesoKg                  float64
Edad                    float64
FechaConsulta    datetime64[us]
dtype: object

In [198]:
# Aserciones (vistas en clase)
assert not df_limpio.isnull().any().any(), "Se encontraron valores nulos en el DataFrame"
assert not df_limpio.duplicated().any(), "Existen filas duplicadas exactas en el dataset"

print("Todas las aserciones pasaron correctamente.")

Todas las aserciones pasaron correctamente.

In [199]:
# Dataset limpio final
df_limpio

   ID_Consulta NombreMascota Especie  PesoKg  Edad FechaConsulta
0          201          Luna   Perro    12.5   5.0    2025-04-01
1          202           Max    Gato     4.2   3.0    2025-02-04
2          203          Milo    Gato     8.1   3.0    2025-04-03
3          204          Nina   Perro     8.1   2.0    2025-04-04
4          206          Luna  Conejo     2.4   1.0    2025-04-05
5          207         Rocky  Conejo     8.1   4.0    2025-04-06
6          208         Simba   Perro    15.0   3.5    2025-04-07
7          209          Mora   Perro     8.1   6.0    2025-04-08
8          210          Luna   Perro    13.0   5.0    2025-04-09

---
## Actividad 11: Análisis básicos sobre el dataset limpio

In [200]:
# Estadísticas descriptivas del dataset limpio
print("=== Estadísticas descriptivas ===")
print(df_limpio.describe())

=== Estadísticas descriptivas ===
       ID_Consulta     PesoKg      Edad        FechaConsulta
count     9.000000   9.000000  9.000000                    9
mean    205.555556   8.833333  3.611111  2025-03-29 16:00:00
min     201.000000   2.400000  1.000000  2025-02-04 00:00:00
25%     203.000000   8.100000  3.000000  2025-04-03 00:00:00
50%     206.000000   8.100000  3.500000  2025-04-05 00:00:00
75%     208.000000  12.500000  5.000000  2025-04-07 00:00:00
max     210.000000  15.000000  6.000000  2025-04-09 00:00:00
std       3.205897   4.090232  1.576741                  NaN

In [201]:
# Cantidad de mascotas por especie
print("\n=== Mascotas por Especie ===")
print(df_limpio["Especie"].value_counts())

=== Mascotas por Especie ===
Especie
Perro     5
Gato      2
Conejo    2
Name: count, dtype: int64

In [202]:
# Peso promedio por especie
print("\n=== Peso promedio por Especie ===")
print(df_limpio.groupby("Especie")["PesoKg"].mean())

=== Peso promedio por Especie ===
Especie
Conejo     5.25
Gato       6.15
Perro     11.34
Name: PesoKg, dtype: float64

In [203]:
# Edad promedio por especie
print("\n=== Edad promedio por Especie ===")
print(df_limpio.groupby("Especie")["Edad"].mean())

=== Edad promedio por Especie ===
Especie
Conejo    2.5
Gato      3.0
Perro     4.3
Name: Edad, dtype: float64

In [204]:
# Comparación media vs mediana del peso (como se vio en clase)
media_peso = df_limpio["PesoKg"].mean()
mediana_peso = df_limpio["PesoKg"].median()
print(f"\n=== Comparación Media vs Mediana (PesoKg) ===")
print(f"Media:   {media_peso:.2f}")
print(f"Mediana: {mediana_peso:.2f}")
if media_peso > mediana_peso:
    print("La media es mayor que la mediana, lo que sugiere valores más altos que tiran el promedio hacia arriba.")
elif media_peso < mediana_peso:
    print("La media es menor que la mediana, lo que sugiere valores más bajos que tiran el promedio hacia abajo.")
else:
    print("Media y mediana son similares, indicando una distribución simétrica.")

=== Comparación Media vs Mediana (PesoKg) ===
Media:   8.83
Mediana: 8.10
La media es mayor que la mediana, lo que sugiere valores más altos que tiran el promedio hacia arriba.

---
## Exportar dataset limpio

Como se vio en clase (Paso 8).

In [205]:
df_limpio.to_csv("mascotas_limpio.csv", index=False)
print("DataFrame exportado a 'mascotas_limpio.csv'")

DataFrame exportado a 'mascotas_limpio.csv'

---
## Técnicas aplicadas

| Paso | Problema detectado | Técnica | Herramienta |
|---|---|---|---|
| Exploración | Visión general del dataset | `head()`, `info()`, `describe()`, `value_counts()` | Pandas |
| Strings | Mayúsculas/minúsculas inconsistentes en Especie | Normalización de texto | `str.strip()`, `str.capitalize()` |
| Nulos | Nulos en NombreMascota, Especie | Imputación con moda | `fillna()` |
| Nulos | Nulos en Edad | Imputación con mediana | `fillna()` |
| Duplicados | Fila con ID_Consulta 204 duplicada | Eliminación | `drop_duplicates()` |
| Tipos | PesoKg almacenado como texto | Conversión numérica | `pd.to_numeric(errors='coerce')` |
| Tipos | FechaConsulta como texto con formatos mixtos | Conversión a datetime | `pd.to_datetime(dayfirst=True, format='mixed')` |
| Valores sospechosos | PesoKg = -3 y Edad = -1 | Reemplazo por mediana | Máscara booleana |
| Validación | Confirmar limpieza completa | Aserciones | `assert` |