# SQL + Pandas — Práctica Guiada
## Sistema de Gestión de Clínica Médica

Este cuaderno acompaña las diapositivas de teoría sobre SQL aplicado a Ingeniería de Datos.

### Objetivos de aprendizaje
Al finalizar esta práctica vas a poder:

- Consultar datos usando `SELECT`, `WHERE`, `ORDER BY` y `LIMIT`
- Construir datasets con `JOIN`
- Crear agregaciones con `GROUP BY` y `HAVING`
- Integrar SQL con Pandas usando `read_sql()`
- Entender cuándo conviene usar SQL y cuándo Pandas

### Idea central de la clase

SQL prepara los datos.  
Pandas los analiza y transforma.

En escenarios reales, los datos viven en bases relacionales y no en archivos CSV aislados.

---
## 1. Conexión

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text

SQLAlchemy es lo que llamamos un ORM (Object Relational Mapper), pero en este pipeline lo usamos como un "traductor" universal.

¿Qué es?: Es una librería que permite a Python hablar con casi cualquier base de datos (MySQL, PostgreSQL, SQLite, Oracle) usando el mismo código.

create_engine: Es el encargado de gestionar la conexión. No conecta inmediatamente, sino que crea un objeto que sabe cómo conectarse cuando sea necesario.

La URL de conexión: Tiene el formato dialecto+driver://usuario:password@host:puerto/nombre_db.

El engine también maneja algo llamado "Connection Pooling", que es básicamente mantener un grupo de conexiones abiertas para no perder tiempo abriendo una nueva cada vez.

In [2]:
try:
    # Ajusta las credenciales según tu entorno
    engine = create_engine('mysql+pymysql://root:@127.0.0.1:3306')
    
    with engine.connect() as conn:
        conn.execute(text('CREATE DATABASE IF NOT EXISTS clinica_db'))
        conn.commit()
    print('Conectado correctamente y base de datos creada.')
except Exception as e:
    print(f"Error de conexión: {e}")
    print("Asegúrate de que el servidor MySQL (XAMPP/WAMP) esté corriendo.")

Conectado correctamente y base de datos creada.

---
## 2. Crear y poblar tablas

Generamos los datos directamente en Python y los cargamos con `to_sql()`. Este es el mismo flujo que usarían si recibieran datos en CSV o Excel y los tuvieran que persistir en la BD.

In [4]:
engine = create_engine(
    'mysql+pymysql://root:@127.0.0.1:3306/clinica_db'
)

print('Conectado a clinica_db')

Conectado a clinica_db

In [5]:
# Tabla pacientes
pacientes = pd.DataFrame({
    'id_paciente':  range(1, 21),
    'nombre': [
        'Ana Gómez', 'Luis Herrera', 'Carmen Díaz', 'Carlos Sosa', 'Marta Ruiz',
        'Pedro Álvarez', 'Julia Torres', 'Roberto Vega', 'Sofía Medina', 'Diego Castro',
        'Laura Ramos', 'Martín Silva', 'Valeria Ríos', 'Facundo Pérez', 'Natalia Blanco',
        'Ignacio López', 'Florencia Mora', 'Sebastián Cruz', 'Daniela Rojas', 'Tomás Ibarra'
    ],
    'edad': [34, 52, 28, 67, 45, 71, 38, 55, 29, 62,
             41, 33, 58, 47, 25, 69, 36, 50, 44, 31],
    'ciudad': [
        'Buenos Aires', 'Córdoba', 'Rosario', 'Buenos Aires', 'Mendoza',
        'Córdoba', 'Rosario', 'Buenos Aires', 'Mendoza', 'Buenos Aires',
        'Córdoba', 'Rosario', 'Buenos Aires', 'Mendoza', 'Córdoba',
        'Rosario', 'Buenos Aires', 'Córdoba', 'Rosario', 'Buenos Aires'
    ],
    'obra_social': [
        'OSDE', 'Swiss Medical', 'PAMI', 'OSDE', 'Medifé',
        'PAMI', 'Swiss Medical', 'OSDE', 'Medifé', 'PAMI',
        'OSDE', 'Swiss Medical', 'Medifé', 'OSDE', 'Swiss Medical',
        'PAMI', 'OSDE', 'Medifé', 'Swiss Medical', None  # paciente sin obra social
    ]
})

pacientes.to_sql('pacientes', engine, if_exists='replace', index=False)
print(f'pacientes: {len(pacientes)} filas')

pacientes: 20 filas

In [6]:
# Tabla medicos
medicos = pd.DataFrame({
    'id_medico':    [1, 2, 3, 4, 5, 6],
    'nombre':       ['Dr. Ramírez', 'Dra. Fernández', 'Dr. González', 'Dra. Martínez', 'Dr. Acosta', 'Dra. Navarro'],
    'especialidad': ['Cardiología', 'Pediatría', 'Clínica Médica', 'Dermatología', 'Traumatología', 'Neurología']
})

medicos.to_sql('medicos', engine, if_exists='replace', index=False)
print(f'medicos: {len(medicos)} filas')

medicos: 6 filas

In [7]:
# Tabla medicamentos
medicamentos = pd.DataFrame({
    'id_medicamento': range(1, 11),
    'nombre':     ['Ibuprofeno', 'Amoxicilina', 'Omeprazol', 'Losartán', 'Metformina',
                   'Atorvastatina', 'Paracetamol', 'Clonazepam', 'Sertralina', 'Diclofenac'],
    'laboratorio':['Bayer', 'Pfizer', 'Gador', 'Roemmers', 'Elea',
                   'Pfizer', 'Bayer', 'Roche', 'Pfizer', 'Novartis'],
    'precio':     [450, 680, 520, 390, 310, 890, 280, 760, 950, 420]
})

medicamentos.to_sql('medicamentos', engine, if_exists='replace', index=False)
print(f'medicamentos: {len(medicamentos)} filas')

medicamentos: 10 filas

In [8]:
# Tabla consultas
import numpy as np
np.random.seed(42)

n = 80
fechas = pd.date_range('2024-01-01', '2025-06-30', periods=n)
diagnosticos = [
    'Hipertensión', 'Diabetes tipo 2', 'Gripe', 'Lumbalgia', 'Gastritis',
    'Dermatitis', 'Ansiedad', 'Control anual', 'Artrosis', 'Migraña'
]

consultas = pd.DataFrame({
    'id_consulta': range(1, n+1),
    'fecha':       fechas,
    'id_paciente': np.random.choice(range(1, 19), n),  # pacientes 19 y 20 sin consulta
    'id_medico':   np.random.choice(range(1, 7), n),
    'diagnostico': np.random.choice(diagnosticos, n),
    'costo':       np.random.choice([2500, 3000, 3500, 4000, 5000], n)
})

consultas.to_sql('consultas', engine, if_exists='replace', index=False)
print(f'consultas: {len(consultas)} filas')

consultas: 80 filas

In [9]:
# Tabla recetas
recetas = pd.DataFrame({
    'id_receta':      range(1, 61),
    'id_consulta':    np.random.choice(range(1, n+1), 60),
    'id_medicamento': np.random.choice(range(1, 11), 60),
    'cantidad':       np.random.choice([1, 2, 3], 60)
})

recetas.to_sql('recetas', engine, if_exists='replace', index=False)
print(f'recetas: {len(recetas)} filas')
print('\n¡Todas las tablas cargadas!')

recetas: 60 filas

¡Todas las tablas cargadas!

---
## 3. SELECT y WHERE — Filtrar antes de traer

**Regla:** nunca traer toda la tabla si solo necesitás un subconjunto. El filtro se hace en SQL, no en Python.

### Operadores disponibles en WHERE

| Operador | Ejemplo |
|---|---|
| `=` | `WHERE ciudad = 'Córdoba'` |
| `>`, `<`, `>=`, `<=` | `WHERE edad >= 60` |
| `<>` | `WHERE obra_social <> 'PAMI'` |
| `LIKE` | `WHERE nombre LIKE 'Dr%'` |
| `IN` | `WHERE ciudad IN ('Córdoba', 'Rosario')` |
| `BETWEEN` | `WHERE costo BETWEEN 3000 AND 4000` |
| `IS NULL` | `WHERE obra_social IS NULL` |
| `AND`, `OR`, `NOT` | Combinar condiciones |

### Concepto clave — Filtrar antes de traer

En Ciencia de Datos, una mala práctica frecuente es traer toda la tabla a Python y filtrar después.

```python
df[df['monto'] > 10000]
```

Eso consume memoria innecesariamente.

La lógica correcta es:

1. Filtrar en SQL
2. Traer menos filas
3. Analizar en Pandas

SQL está optimizado para hacer ese trabajo en el servidor.

In [13]:
# Ejemplo 1: pacientes mayores de 60 años
df = pd.read_sql("""
    SELECT nombre, edad, ciudad, obra_social
    FROM pacientes
    WHERE edad > 60
    ORDER BY edad DESC
""", engine)
print(f'Pacientes > 60 años: {len(df)}')
df

Pacientes > 60 años: 4

          nombre  edad        ciudad obra_social
0  Pedro Álvarez    71       Córdoba        PAMI
1  Ignacio López    69       Rosario        PAMI
2    Carlos Sosa    67  Buenos Aires        OSDE
3   Diego Castro    62  Buenos Aires        PAMI

In [14]:
# Ejemplo 2: LIKE — médicos cuyo nombre empieza con 'Dra'
df = pd.read_sql("""
    SELECT nombre, especialidad
    FROM medicos
    WHERE nombre LIKE 'Dra%%'
""", engine)
df

           nombre  especialidad
0  Dra. Fernández     Pediatría
1   Dra. Martínez  Dermatología
2    Dra. Navarro    Neurología

In [12]:
# Ejemplo 3: IN — pacientes de Córdoba o Mendoza
df = pd.read_sql("""
    SELECT nombre, ciudad, obra_social
    FROM pacientes
    WHERE ciudad IN ('Córdoba', 'Mendoza')
    ORDER BY ciudad
    LIMIT 5
""", engine)
df

           nombre   ciudad    obra_social
0    Luis Herrera  Córdoba  Swiss Medical
1   Pedro Álvarez  Córdoba           PAMI
2     Laura Ramos  Córdoba           OSDE
3  Natalia Blanco  Córdoba  Swiss Medical
4  Sebastián Cruz  Córdoba         Medifé

In [15]:
# Ejemplo 4: BETWEEN — consultas con costo entre 3000 y 4000
df = pd.read_sql("""
    SELECT id_consulta, fecha, diagnostico, costo
    FROM consultas
    WHERE costo BETWEEN 3000 AND 4000
    ORDER BY costo DESC
""", engine)
print(f'Consultas entre $3000 y $4000: {len(df)}')
df.head()

Consultas entre $3000 y $4000: 44

   id_consulta               fecha      diagnostico  costo
0            1 2024-01-01 00:00:00         Artrosis   4000
1           10 2024-03-03 04:51:38        Lumbalgia   4000
2           12 2024-03-17 00:36:27     Hipertensión   4000
3           15 2024-04-06 18:13:40         Ansiedad   4000
4           16 2024-04-13 16:06:04  Diabetes tipo 2   4000

In [16]:
# Ejemplo 5: IS NULL — pacientes sin obra social
df = pd.read_sql("""
    SELECT nombre, edad, ciudad
    FROM pacientes
    WHERE obra_social IS NULL
""", engine)
print(f'Pacientes sin obra social: {len(df)}')
df

Pacientes sin obra social: 1

         nombre  edad        ciudad
0  Tomás Ibarra    31  Buenos Aires

In [17]:
# Ejemplo 6: AND + OR — pacientes de OSDE mayores de 40
df = pd.read_sql("""
    SELECT nombre, edad, ciudad, obra_social
    FROM pacientes
    WHERE obra_social = 'OSDE' AND edad > 40
    ORDER BY edad DESC
""", engine)
df

          nombre  edad        ciudad obra_social
0    Carlos Sosa    67  Buenos Aires        OSDE
1   Roberto Vega    55  Buenos Aires        OSDE
2  Facundo Pérez    47       Mendoza        OSDE
3    Laura Ramos    41       Córdoba        OSDE

---
## 4. GROUP BY y HAVING — Agregar en el servidor

`GROUP BY` agrupa filas y aplica funciones de agregación (`COUNT`, `SUM`, `AVG`, `MIN`, `MAX`).
`HAVING` filtra **grupos** (como `WHERE` pero para el resultado de `GROUP BY`).

```sql
SELECT columna, COUNT(*) AS cantidad
FROM tabla
GROUP BY columna
HAVING cantidad > 5
```

> **Diferencia clave:** `WHERE` filtra filas antes de agrupar. `HAVING` filtra grupos después de agregar.

In [18]:
# Ejemplo 1: cantidad de consultas por médico
df = pd.read_sql("""
    SELECT
        m.nombre,
        m.especialidad,
        COUNT(*) AS total_consultas,
        AVG(c.costo) AS costo_promedio,
        SUM(c.costo) AS facturacion_total
    FROM consultas c
    JOIN medicos m ON c.id_medico = m.id_medico
    GROUP BY m.id_medico, m.nombre, m.especialidad
    ORDER BY total_consultas DESC
""", engine)
df['costo_promedio'] = df['costo_promedio'].round(0)
df

,nombre,especialidad,total_consultas,costo_promedio,facturacion_total
0,Dr. Ramírez,Cardiología,15,3200.0,48000.0
1,Dr. González,Clínica Médica,15,3533.0,53000.0
2,Dra. Martínez,Dermatología,15,3833.0,57500.0
3,Dr. Acosta,Traumatología,13,3923.0,51000.0
4,Dra. Navarro,Neurología,13,3385.0,44000.0
5,Dra. Fernández,Pediatría,9,3944.0,35500.0

### Concepto clave — GROUP BY y ingeniería de variables (feature engineering)

`GROUP BY` transforma datos transaccionales en variables útiles para análisis y Machine Learning.

Ejemplos típicos:

- cantidad de consultas por paciente
- gasto total
- promedio por especialidad
- fecha de última atención

Estas agregaciones suelen construirse directamente en SQL antes de pasar a Pandas.

In [19]:
# Ejemplo 2: HAVING — médicos con más de 12 consultas
df = pd.read_sql("""
    SELECT
        m.nombre,
        m.especialidad,
        COUNT(*) AS total_consultas
    FROM consultas c
    JOIN medicos m ON c.id_medico = m.id_medico
    GROUP BY m.id_medico, m.nombre, m.especialidad
    HAVING total_consultas > 12
    ORDER BY total_consultas DESC
""", engine)
print('Médicos con más de 12 consultas:')
df

Médicos con más de 12 consultas:

          nombre    especialidad  total_consultas
0    Dr. Ramírez     Cardiología               15
1   Dr. González  Clínica Médica               15
2  Dra. Martínez    Dermatología               15
3     Dr. Acosta   Traumatología               13
4   Dra. Navarro      Neurología               13

In [20]:
# Ejemplo 3: diagnóstico más frecuente
df = pd.read_sql("""
    SELECT
        diagnostico,
        COUNT(*) AS frecuencia,
        AVG(costo) AS costo_promedio
    FROM consultas
    GROUP BY diagnostico
    ORDER BY frecuencia DESC
""", engine)
df['costo_promedio'] = df['costo_promedio'].round(0)
df

       diagnostico  frecuencia  costo_promedio
0     Hipertensión          15          3467.0
1        Lumbalgia           9          3611.0
2            Gripe           8          3688.0
3         Ansiedad           8          3625.0
4  Diabetes tipo 2           8          3875.0
5         Artrosis           7          3786.0
6    Control anual           7          3286.0
7       Dermatitis           7          3571.0
8          Migraña           6          3417.0
9        Gastritis           5          4000.0

In [21]:
# Ejemplo 4: WHERE vs HAVING — diferencia práctica
# WHERE: filtra filas ANTES de agrupar
# HAVING: filtra grupos DESPUÉS de agregar

# Solo consultas de 2025, agrupadas por mes, con más de 3 consultas ese mes
df = pd.read_sql("""
    SELECT
        MONTH(fecha) AS mes,
        COUNT(*) AS consultas_en_2025
    FROM consultas
    WHERE YEAR(fecha) = 2025
    GROUP BY mes
    HAVING consultas_en_2025 > 3
    ORDER BY mes
""", engine)
df

   mes  consultas_en_2025
0    1                  5
1    2                  4
2    3                  4
3    4                  5
4    5                  4
5    6                  5

---
## 5. JOINs — Combinar tablas

Recordá que `JOIN` en SQL es el equivalente de `merge()` en Pandas.

| SQL | Pandas | Resultado |
|---|---|---|
| `INNER JOIN` | `how='inner'` | Solo filas con coincidencia en ambas tablas |
| `LEFT JOIN` | `how='left'` | Todas las filas de la tabla izquierda |
| `RIGHT JOIN` | `how='right'` | Todas las filas de la tabla derecha |
| `FULL OUTER JOIN` | `how='outer'` | Todo, NaN donde no hay coincidencia |

In [22]:
# INNER JOIN: consultas con datos completos de paciente y médico
df = pd.read_sql("""
    SELECT
        c.id_consulta,
        c.fecha,
        p.nombre AS paciente,
        p.obra_social,
        m.nombre AS medico,
        m.especialidad,
        c.diagnostico,
        c.costo
    FROM consultas c
    INNER JOIN pacientes p ON c.id_paciente = p.id_paciente
    INNER JOIN medicos m   ON c.id_medico   = m.id_medico
    ORDER BY c.fecha DESC
""", engine)
print(f'Filas resultado: {len(df)}')
df.head()

Filas resultado: 80

,id_consulta,fecha,paciente,obra_social,medico,especialidad,diagnostico,costo
0,80,2025-06-30 00:00:00,Carmen Díaz,PAMI,Dr. González,Clínica Médica,Hipertensión,3500
1,79,2025-06-23 02:07:35,Carmen Díaz,PAMI,Dra. Navarro,Neurología,Diabetes tipo 2,3000
2,78,2025-06-16 04:15:11,Roberto Vega,OSDE,Dr. González,Clínica Médica,Hipertensión,3000
3,77,2025-06-09 06:22:47,Florencia Mora,OSDE,Dr. Ramírez,Cardiología,Lumbalgia,2500
4,76,2025-06-02 08:30:22,Laura Ramos,OSDE,Dr. Acosta,Traumatología,Artrosis,3000

In [23]:
# LEFT JOIN: todos los pacientes, hayan tenido consulta o no
# Los pacientes sin consulta aparecen con NaN en los campos de consulta
df = pd.read_sql("""
    SELECT
        p.nombre AS paciente,
        p.ciudad,
        c.id_consulta,
        c.fecha,
        c.diagnostico
    FROM pacientes p
    LEFT JOIN consultas c ON p.id_paciente = c.id_paciente
""", engine)

# Identificar pacientes sin ninguna consulta
sin_consulta = df[df['id_consulta'].isna()][['paciente', 'ciudad']].drop_duplicates()
print(f'Pacientes sin consulta registrada: {len(sin_consulta)}')
print(sin_consulta)

Pacientes sin consulta registrada: 2
         paciente        ciudad
80  Daniela Rojas       Rosario
81   Tomás Ibarra  Buenos Aires

### Concepto clave — JOINs y modelo relacional

En bases de datos reales, la información está distribuida en múltiples tablas.

Por ejemplo:

- pacientes
- médicos
- consultas
- recetas

Para construir un dataset completo necesitás relacionarlas usando `JOIN`.

### Idea importante para DS

`LEFT JOIN` suele ser más útil que `INNER JOIN`, porque preserva registros aunque no tengan coincidencias.

In [24]:
# JOIN con 3 tablas: recetas con medicamentos y consultas
df = pd.read_sql("""
    SELECT
        p.nombre AS paciente,
        c.fecha,
        c.diagnostico,
        med.nombre AS medicamento,
        med.laboratorio,
        r.cantidad,
        (med.precio * r.cantidad) AS costo_receta
    FROM recetas r
    JOIN consultas c    ON r.id_consulta    = c.id_consulta
    JOIN pacientes p    ON c.id_paciente    = p.id_paciente
    JOIN medicamentos med ON r.id_medicamento = med.id_medicamento
    ORDER BY costo_receta DESC
""", engine)
print(f'Recetas totales: {len(df)}')
df.head(8)

Recetas totales: 60

,paciente,fecha,diagnostico,medicamento,laboratorio,cantidad,costo_receta
0,Laura Ramos,2024-02-11 11:14:25,Dermatitis,Sertralina,Pfizer,3,2850
1,Carlos Sosa,2024-02-18 09:06:50,Control anual,Atorvastatina,Pfizer,3,2670
2,Martín Silva,2024-12-18 11:32:39,Lumbalgia,Clonazepam,Roche,3,2280
3,Valeria Ríos,2025-03-04 12:09:06,Control anual,Sertralina,Pfizer,2,1900
4,Sebastián Cruz,2024-08-02 06:04:33,Diabetes tipo 2,Atorvastatina,Pfizer,2,1780
5,Sebastián Cruz,2024-08-02 06:04:33,Diabetes tipo 2,Omeprazol,Gador,3,1560
6,Valeria Ríos,2025-03-25 05:46:19,Control anual,Omeprazol,Gador,3,1560
7,Ignacio López,2025-01-22 00:54:41,Gripe,Clonazepam,Roche,2,1520

---
## 6. SQL Pushdown vs Pandas — Comparación

Ambos métodos dan el mismo resultado. La diferencia es **quién hace el trabajo** y cuánta memoria/red se usa.

In [25]:
# Pregunta: ¿cuánto facturó cada especialidad médica?

# MÉTODO A: Sin pushdown (lento con tablas grandes)
df_consultas = pd.read_sql('SELECT * FROM consultas', engine)
df_medicos   = pd.read_sql('SELECT * FROM medicos', engine)

resultado_pandas = (
    df_consultas
    .merge(df_medicos, on='id_medico')
    .groupby('especialidad')['costo']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)
print('Método A (Pandas):')
print(resultado_pandas)

# MÉTODO B: Con pushdown (eficiente)
resultado_sql = pd.read_sql("""
    SELECT
        m.especialidad,
        SUM(c.costo) AS facturacion_total
    FROM consultas c
    JOIN medicos m ON c.id_medico = m.id_medico
    GROUP BY m.especialidad
    ORDER BY facturacion_total DESC
""", engine)
print('\nMétodo B (SQL Pushdown):')
print(resultado_sql)

Método A (Pandas):
     especialidad  costo
0    Dermatología  57500
1  Clínica Médica  53000
2   Traumatología  51000
3     Cardiología  48000
4      Neurología  44000
5       Pediatría  35500

Método B (SQL Pushdown):
     especialidad  facturacion_total
0    Dermatología            57500.0
1  Clínica Médica            53000.0
2   Traumatología            51000.0
3     Cardiología            48000.0
4      Neurología            44000.0
5       Pediatría            35500.0

---
## 7. Queries parametrizadas — Buena práctica

En lugar de construir strings con f-strings (riesgo de inyección SQL), usamos parámetros.

```python
# MAL — vulnerable a SQL injection
query = f"SELECT * FROM pacientes WHERE ciudad = '{ciudad}'"

# MEJOR — parametrizado
query = "SELECT * FROM pacientes WHERE ciudad = :ciudad"
df = pd.read_sql(query, engine, params={'ciudad': ciudad})
```

In [26]:
# Función reutilizable: consultas por ciudad
def consultas_por_ciudad(ciudad: str):

    query = text("""
        SELECT
            p.nombre AS paciente,
            p.ciudad,
            COUNT(c.id_consulta) AS total_consultas,
            SUM(c.costo) AS gasto_total
        FROM pacientes p
        LEFT JOIN consultas c
            ON p.id_paciente = c.id_paciente
        WHERE p.ciudad = :ciudad
        GROUP BY p.id_paciente, p.nombre, p.ciudad
        ORDER BY total_consultas DESC
    """)

    return pd.read_sql(
        query,
        engine,
        params={'ciudad': ciudad}
    )

print('Consultas en Buenos Aires:')
display(consultas_por_ciudad('Buenos Aires'))

Consultas en Buenos Aires:

         paciente        ciudad  total_consultas  gasto_total
0    Roberto Vega  Buenos Aires                8      30500.0
1     Carlos Sosa  Buenos Aires                6      20000.0
2       Ana Gómez  Buenos Aires                3      11500.0
3  Florencia Mora  Buenos Aires                3       8500.0
4    Diego Castro  Buenos Aires                3      12000.0
5    Valeria Ríos  Buenos Aires                3       9000.0
6    Tomás Ibarra  Buenos Aires                0          NaN

## 8. Construcción del Dataset Completo con Pandas: `merge()`

En esta sección, nos enfocaremos en cómo construir un dataset completo utilizando la función `merge()` de Pandas. Si bien SQL es la herramienta preferida para filtrar y agregar grandes volúmenes de datos directamente en la base de datos (lo que conocemos como SQL Pushdown), Pandas `merge()` se vuelve esencial cuando los datos ya han sido traídos al entorno de Python y necesitamos ensamblar tablas para un análisis más profundo o para la ingeniería de características.

Esta aproximación complementa el uso de SQL: primero, SQL se encarga de las operaciones pesadas y de reducir el volumen de datos. Luego, Pandas toma el control para combinar estas piezas, realizar transformaciones complejas y preparar el dataset final para modelos de Machine Learning u otros análisis avanzados. Aquí, la idea es consolidar la información dispersa en diferentes DataFrames en una estructura unificada y coherente.

### Ejemplo Básico: Uniendo `consultas` con `pacientes` 
Antes de construir el dataset complejo, veamos un ejemplo simple de cómo funciona `merge()`. Aquí uniremos `df_consultas` con `df_pacientes` para agregar información básica del paciente a cada consulta.

In [35]:
df_consultas_1 = pd.read_sql(
    """SELECT id_consulta, fecha, id_paciente, diagnostico, costo
    FROM consultas
    WHERE YEAR(fecha) = 2025
    """, engine
)

df_pacientes_1 = pd.read_sql(
    """SELECT id_paciente, nombre, edad, ciudad, obra_social
    FROM pacientes
    WHERE edad > 30 AND ciudad = 'Buenos Aires'
    """, engine
)

ejemplo_merge = df_consultas_1.merge(
    df_pacientes_1[['id_paciente', 'nombre', 'edad', 'ciudad']],
    on='id_paciente',
    how='inner'
)

print(f'Filas de consultas (filtradas): {len(df_consultas_1)}')
print(f'Filas de pacientes (filtrados): {len(df_pacientes_1)}')
print(f'Filas después del merge: {len(ejemplo_merge)}')
display(ejemplo_merge.head())

Filas de consultas (filtradas): 27
Filas de pacientes (filtrados): 7
Filas después del merge: 12

,id_consulta,fecha,id_paciente,diagnostico,costo,nombre,edad,ciudad
0,54,2025-01-01 07:17:28,10,Gripe,3500,Diego Castro,62,Buenos Aires
1,55,2025-01-08 05:09:52,4,Migraña,2500,Carlos Sosa,67,Buenos Aires
2,59,2025-02-04 20:39:29,8,Ansiedad,5000,Roberto Vega,55,Buenos Aires
3,61,2025-02-18 16:24:18,8,Artrosis,3500,Roberto Vega,55,Buenos Aires
4,63,2025-03-04 12:09:06,13,Control anual,2500,Valeria Ríos,58,Buenos Aires

### Paso 1: Combinar las tablas principales (`consultas`, `pacientes`, `medicos`)
Aquí empezamos a construir nuestro dataset completo. La tabla `consultas` es nuestra base porque contiene las claves foráneas (FK) que nos permiten conectarla con `pacientes` y `medicos`. Usamos un `INNER JOIN` para asegurarnos de que cada consulta tenga un paciente y un médico válidos.

#### Validación de Integridad de Datos (`validate`)

El parámetro validate permite verificar la integridad relacional de los DataFrames antes de realizar la unión. Esto previene la creación accidental de datos duplicados (productos cartesianos).

**¿Qué estamos validando?**
* **Many (Izquierda - `df_consultas`):** Es normal y esperado que un paciente tenga múltiples registros (varias consultas).
* **One (Derecha - `df_pacientes`):** Garantizamos que cada paciente sea **único** en el catálogo maestro.

**¿Por qué es importante?**
 Si por error existieran duplicados en la tabla de pacientes, Pandas arrojaría un `MergeError` en lugar de crear filas duplicadas artificialmente. Esto evita errores comunes de duplicidad en análisis estadísticos y financieros.

In [ ]:
df_consultas

In [36]:
# Partimos de consultas (la tabla central — tiene las FK)
df = (
    df_consultas_1
    .merge(
        df_pacientes_1,
        on='id_paciente',
        how='inner',              
        validate='many_to_one'    
    )
    
)

In [32]:
df.merge(
        df_medicos,
        on='id_medico',
        how='inner',
        validate='many_to_one'    
    )

,id_consulta,fecha,id_paciente,id_medico,diagnostico,costo,nombre_x,edad,ciudad,obra_social,nombre_y,especialidad
0,4,2024-01-21 17:37:12,8,2,Gripe,3500,Roberto Vega,55,Buenos Aires,OSDE,Dra. Fernández,Pediatría
1,8,2024-02-18 09:06:50,4,1,Control anual,3500,Carlos Sosa,67,Buenos Aires,OSDE,Dr. Ramírez,Cardiología
2,9,2024-02-25 06:59:14,8,4,Artrosis,3500,Roberto Vega,55,Buenos Aires,OSDE,Dra. Martínez,Dermatología
3,15,2024-04-06 18:13:40,1,4,Ansiedad,4000,Ana Gómez,34,Buenos Aires,OSDE,Dra. Martínez,Dermatología
4,18,2024-04-27 11:50:53,17,3,Hipertensión,2500,Florencia Mora,36,Buenos Aires,OSDE,Dr. González,Clínica Médica
5,19,2024-05-04 09:43:17,10,1,Gastritis,3500,Diego Castro,62,Buenos Aires,PAMI,Dr. Ramírez,Cardiología
6,30,2024-07-19 10:19:44,4,2,Hipertensión,4000,Carlos Sosa,67,Buenos Aires,OSDE,Dra. Fernández,Pediatría
7,38,2024-09-12 17:18:59,8,4,Ansiedad,3500,Roberto Vega,55,Buenos Aires,OSDE,Dra. Martínez,Dermatología
8,42,2024-10-10 08:48:36,17,3,Control anual,3500,Florencia Mora,36,Buenos Aires,OSDE,Dr. González,Clínica Médica
9,43,2024-10-17 06:41:00,4,5,Gastritis,3500,Carlos Sosa,67,Buenos Aires,OSDE,Dr. Acosta,Traumatología
10,45,2024-10-31 02:25:49,8,5,Diabetes tipo 2,5000,Roberto Vega,55,Buenos Aires,OSDE,Dr. Acosta,Traumatología
11,46,2024-11-07 00:18:13,4,3,Dermatitis,2500,Carlos Sosa,67,Buenos Aires,OSDE,Dr. González,Clínica Médica
12,49,2024-11-27 17:55:26,10,4,Artrosis,5000,Diego Castro,62,Buenos Aires,PAMI,Dra. Martínez,Dermatología
13,50,2024-12-04 15:47:50,4,2,Dermatitis,4000,Carlos Sosa,67,Buenos Aires,OSDE,Dra. Fernández,Pediatría
14,54,2025-01-01 07:17:28,10,1,Gripe,3500,Diego Castro,62,Buenos Aires,PAMI,Dr. Ramírez,Cardiología
15,55,2025-01-08 05:09:52,4,5,Migraña,2500,Carlos Sosa,67,Buenos Aires,OSDE,Dr. Acosta,Traumatología
16,59,2025-02-04 20:39:29,8,4,Ansiedad,5000,Roberto Vega,55,Buenos Aires,OSDE,Dra. Martínez,Dermatología
17,61,2025-02-18 16:24:18,8,4,Artrosis,3500,Roberto Vega,55,Buenos Aires,OSDE,Dra. Martínez,Dermatología
18,63,2025-03-04 12:09:06,13,6,Control anual,2500,Valeria Ríos,58,Buenos Aires,Medifé,Dra. Navarro,Neurología
19,66,2025-03-25 05:46:19,13,4,Control anual,2500,Valeria Ríos,58,Buenos Aires,Medifé,Dra. Martínez,Dermatología
20,69,2025-04-14 23:23:32,13,1,Artrosis,4000,Valeria Ríos,58,Buenos Aires,Medifé,Dr. Ramírez,Cardiología
21,70,2025-04-21 21:15:56,1,1,Diabetes tipo 2,2500,Ana Gómez,34,Buenos Aires,OSDE,Dr. Ramírez,Cardiología
22,73,2025-05-12 14:53:09,1,6,Gripe,5000,Ana Gómez,34,Buenos Aires,OSDE,Dra. Navarro,Neurología
23,75,2025-05-26 10:37:58,8,4,Migraña,3500,Roberto Vega,55,Buenos Aires,OSDE,Dra. Martínez,Dermatología
24,77,2025-06-09 06:22:47,17,1,Lumbalgia,2500,Florencia Mora,36,Buenos Aires,OSDE,Dr. Ramírez,Cardiología
25,78,2025-06-16 04:15:11,8,3,Hipertensión,3000,Roberto Vega,55,Buenos Aires,OSDE,Dr. González,Clínica Médica

### Paso 2: Incorporar información sobre recetas (`recetas`)
A continuación, queremos saber si cada consulta generó una receta. Usamos un `LEFT JOIN` para mantener todas las consultas que ya tenemos (nuestra tabla 'izquierda') y añadir una columna que indique si existe una receta asociada. Esto nos permite ver las consultas incluso si no tienen receta.

In [33]:
# LEFT JOIN: queremos TODAS las consultas,
# aunque no tengan receta asociada
df_recetas = pd.read_sql('SELECT * FROM recetas', engine)
df = df.merge(
    df_recetas['id_consulta'].drop_duplicates()
              .to_frame()
              .assign(tiene_receta=True),
    on='id_consulta',
    how='left',
    validate='many_to_one'
)

# Rellenar NaN → False para consultas sin receta
df['tiene_receta'] = df['tiene_receta'].fillna(False)

C:\Users\csaez\AppData\Local\Temp\ipykernel_21212\3983462708.py:14: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['tiene_receta'] = df['tiene_receta'].fillna(False)

### Paso 3: Validar la integridad del dataset construido
Es crucial verificar que el proceso de combinación de tablas se realizó correctamente. En este paso, validamos que el DataFrame resultante tenga las dimensiones esperadas, que no haya valores nulos inesperados en columnas clave, y que no se hayan duplicado o perdido registros durante los `JOIN`s. Esto asegura la calidad de los datos para análisis posteriores.

In [34]:
# 1. Dimensiones
print(f"Filas: {len(df)}")
print(f"Columnas: {df.columns.tolist()}")

# 2. No deben quedar NaN en columnas críticas
criticas = ['id_consulta', 'id_paciente', 'id_medico', 'diagnostico']
nulos = df[criticas].isnull().sum()
assert nulos.sum() == 0, f"NaN inesperados: {nulos[nulos>0]}"

# 3. id_consulta debe ser único (no duplicar filas)
assert df['id_consulta'].duplicated().sum() == 0, \
    "Hay id_consulta duplicados — revisar el merge"

# 4. Conteo debe coincidir con df_consultas limpio
assert len(df) == len(df_consultas), \
    f"Perdiste filas: esperado {len(df_consultas)}, got {len(df)}"

# 5. _merge indicator (solo si usás indicator=True)
df_check = df_consultas.merge(
    df_pacientes, on='id_paciente', how='left', indicator=True
)
print(df_check['_merge'].value_counts())
# left_only → consultas con id_paciente inválido (problema de integridad)

Filas: 26
Columnas: ['id_consulta', 'fecha', 'id_paciente', 'id_medico', 'diagnostico', 'costo', 'nombre', 'edad', 'ciudad', 'obra_social', 'tiene_receta']

AssertionError: Perdiste filas: esperado 80, got 26

## Ejercicios propuestos

Intentá resolver cada ejercicio antes de revisar la solución.

### Estrategia recomendada
1. Leer el enunciado
2. Pensar qué operación SQL corresponde
3. Ejecutar la consulta
4. Validar el resultado en Pandas

La práctica constante es la forma más rápida de aprender SQL.

---
## 8. Ejercicios de práctica

Resolvé cada ejercicio usando SQL + `pd.read_sql()`. Intentá hacerlo sin ver la solución.

### Ejercicio 1 — WHERE básico
**Consigna:** Traé todos los pacientes mayores de 50 años que tengan PAMI como obra social, ordenados por edad de mayor a menor.

In [ ]:
# Tu código acá

### Ejercicio 2 — LIKE e IN
**Consigna:** Traé los medicamentos del laboratorio Pfizer o Bayer cuyo precio sea mayor a 500. Mostrá nombre, laboratorio y precio.

In [ ]:
# Tu código acá

### Ejercicio 3 — GROUP BY
**Consigna:** Calculá la cantidad de consultas y el costo promedio por ciudad de los pacientes. Ordená por cantidad de consultas descendente.

In [ ]:
# Tu código acá

### Ejercicio 4 — HAVING
**Consigna:** Mostrá solo los diagnósticos que aparecen más de 8 veces en la tabla de consultas. Incluí la frecuencia y el costo promedio.

In [ ]:
# Tu código acá

### Ejercicio 5 — JOIN con 2 tablas
**Consigna:** Listá el nombre del paciente, el nombre del médico, la especialidad y el diagnóstico para todas las consultas del año 2024. Ordená por fecha.

In [ ]:
# Tu código acá

### Ejercicio 6 — LEFT JOIN
**Consigna:** Mostrá todos los médicos y cuántas consultas tiene cada uno. Incluí también los médicos que no tienen ninguna consulta (si los hay).

In [ ]:
# Tu código acá

### Ejercicio 7 — JOIN con 3 tablas + GROUP BY
**Consigna:** ¿Qué laboratorio facturó más en recetas? Calculá el total facturado (precio × cantidad) por laboratorio, ordenado de mayor a menor.

In [ ]:
# Tu código acá

### Ejercicio 8 — Pushdown vs Pandas
**Consigna:** Respondé esta pregunta de dos maneras:
- **Método A:** trayendo todas las tablas y resolviendo en Pandas
- **Método B:** resolviendo directamente en SQL con pushdown

**Pregunta:** ¿Cuál es la obra social cuyos pacientes tienen el mayor gasto promedio por consulta?

In [ ]:
# Método A: Pandas

In [ ]:
# Método B: SQL Pushdown

### Ejercicio 9 — Query parametrizada
**Consigna:** Escribí una función `buscar_por_especialidad(especialidad)` que reciba una especialidad médica y devuelva un DataFrame con el nombre del paciente, fecha, diagnóstico y costo de todas las consultas con ese médico. Usá query parametrizada.

In [ ]:
# Tu código acá

### Ejercicio 10 — Integrador
**Consigna:** Construí un dataset listo para un modelo de ML que prediga el costo de una consulta. Debe incluir:
- Edad del paciente
- Si tiene obra social (1/0)
- Especialidad del médico
- Cantidad de consultas previas del paciente
- Costo de la consulta (variable target)

Usá SQL para construir la mayor parte posible del dataset antes de traerlo a Python.

## Soluciones explicadas

Las soluciones no solo muestran el código correcto.

También explican:

- por qué funciona la consulta
- qué cláusulas intervienen
- cómo se relaciona con Pandas
- qué buenas prácticas se aplican

In [ ]:
# Tu código acá

---
## 9. Soluciones

#### Solución Ejercicio 1

Analizá la lógica de la consulta antes de ejecutar la siguiente celda.

In [ ]:
pd.read_sql("""
    SELECT nombre, edad, ciudad, obra_social
    FROM pacientes
    WHERE edad > 50 AND obra_social = 'PAMI'
    ORDER BY edad DESC
""", engine)

#### Solución Ejercicio 2

Analizá la lógica de la consulta antes de ejecutar la siguiente celda.

In [ ]:
pd.read_sql("""
    SELECT nombre, laboratorio, precio
    FROM medicamentos
    WHERE laboratorio IN ('Pfizer', 'Bayer') AND precio > 500
    ORDER BY precio DESC
""", engine)

#### Solución Ejercicio 3

Analizá la lógica de la consulta antes de ejecutar la siguiente celda.

In [ ]:
pd.read_sql("""
    SELECT
        p.ciudad,
        COUNT(c.id_consulta) AS cantidad_consultas,
        ROUND(AVG(c.costo), 0) AS costo_promedio
    FROM pacientes p
    JOIN consultas c ON p.id_paciente = c.id_paciente
    GROUP BY p.ciudad
    ORDER BY cantidad_consultas DESC
""", engine)

#### Solución Ejercicio 4

Analizá la lógica de la consulta antes de ejecutar la siguiente celda.

In [ ]:
pd.read_sql("""
    SELECT
        diagnostico,
        COUNT(*) AS frecuencia,
        ROUND(AVG(costo), 0) AS costo_promedio
    FROM consultas
    GROUP BY diagnostico
    HAVING frecuencia > 8
    ORDER BY frecuencia DESC
""", engine)

#### Solución Ejercicio 5

Analizá la lógica de la consulta antes de ejecutar la siguiente celda.

In [ ]:
pd.read_sql("""
    SELECT
        p.nombre AS paciente,
        m.nombre AS medico,
        m.especialidad,
        c.diagnostico,
        c.fecha
    FROM consultas c
    JOIN pacientes p ON c.id_paciente = p.id_paciente
    JOIN medicos m   ON c.id_medico   = m.id_medico
    WHERE YEAR(c.fecha) = 2024
    ORDER BY c.fecha
""", engine)

#### Solución Ejercicio 6

Analizá la lógica de la consulta antes de ejecutar la siguiente celda.

In [ ]:
pd.read_sql("""
    SELECT
        m.nombre AS medico,
        m.especialidad,
        COUNT(c.id_consulta) AS total_consultas
    FROM medicos m
    LEFT JOIN consultas c ON m.id_medico = c.id_medico
    GROUP BY m.id_medico, m.nombre, m.especialidad
    ORDER BY total_consultas DESC
""", engine)

#### Solución Ejercicio 7

Analizá la lógica de la consulta antes de ejecutar la siguiente celda.

In [ ]:
pd.read_sql("""
    SELECT
        med.laboratorio,
        SUM(med.precio * r.cantidad) AS facturacion_total
    FROM recetas r
    JOIN medicamentos med ON r.id_medicamento = med.id_medicamento
    GROUP BY med.laboratorio
    ORDER BY facturacion_total DESC
""", engine)

#### Solución Ejercicio 8

Analizá la lógica de la consulta antes de ejecutar la siguiente celda.

In [ ]:
# Método A: Pandas
df_p = pd.read_sql('SELECT * FROM pacientes', engine)
df_c = pd.read_sql('SELECT * FROM consultas', engine)

resultado_a = (
    df_p.merge(df_c, on='id_paciente')
    .groupby('obra_social')['costo']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
    .rename(columns={'costo': 'gasto_promedio'})
)
resultado_a['gasto_promedio'] = resultado_a['gasto_promedio'].round(0)
print('Método A:')
display(resultado_a)

# Método B: SQL Pushdown
resultado_b = pd.read_sql("""
    SELECT
        p.obra_social,
        ROUND(AVG(c.costo), 0) AS gasto_promedio
    FROM consultas c
    JOIN pacientes p ON c.id_paciente = p.id_paciente
    WHERE p.obra_social IS NOT NULL
    GROUP BY p.obra_social
    ORDER BY gasto_promedio DESC
""", engine)
print('\nMétodo B:')
display(resultado_b)

#### Solución Ejercicio 9

Analizá la lógica de la consulta antes de ejecutar la siguiente celda.

In [ ]:
def buscar_por_especialidad(especialidad: str):
    query = """
        SELECT
            p.nombre AS paciente,
            c.fecha,
            c.diagnostico,
            c.costo
        FROM consultas c
        JOIN pacientes p ON c.id_paciente = p.id_paciente
        JOIN medicos m   ON c.id_medico   = m.id_medico
        WHERE m.especialidad = :especialidad
        ORDER BY c.fecha DESC
    """
    return pd.read_sql(query, engine, params={'especialidad': especialidad})

display(buscar_por_especialidad('Cardiología'))

#### Solución Ejercicio 10

Analizá la lógica de la consulta antes de ejecutar la siguiente celda.

In [ ]:
# La mayor parte se construye en SQL
df_ml = pd.read_sql("""
    SELECT
        c.id_consulta,
        p.edad,
        CASE WHEN p.obra_social IS NOT NULL THEN 1 ELSE 0 END AS tiene_obra_social,
        m.especialidad,
        c.costo AS costo_consulta,
        (
            SELECT COUNT(*)
            FROM consultas c2
            WHERE c2.id_paciente = c.id_paciente
              AND c2.fecha < c.fecha
        ) AS consultas_previas
    FROM consultas c
    JOIN pacientes p ON c.id_paciente = p.id_paciente
    JOIN medicos m   ON c.id_medico   = m.id_medico
    ORDER BY c.id_consulta
""", engine)

print(f'Dataset para ML: {df_ml.shape}')
print('Columnas:', df_ml.columns.tolist())
display(df_ml.head())

# get_dummies para la columna categórica
df_ml = pd.get_dummies(df_ml, columns=['especialidad'], drop_first=True)
bool_cols = df_ml.select_dtypes(include='bool').columns
df_ml[bool_cols] = df_ml[bool_cols].astype(int)
print(f'\nDespués de get_dummies: {df_ml.shape} columnas')
df_ml.head()

---
## Cierre del Motor

In [ ]:
engine.dispose()
print("\n🔌 Conexión cerrada correctamente.")