# Pandas - Repaso y más
Pandas es una librería de Python especializada en el manejo y análisis de estructuras de datos.

Pandas tiene dos estructuras de datos principales:
- **`Series`**: arreglo unidimensional etiquetado (como una columna)
- **`DataFrame`**: tabla bidimensional con etiquetas en filas y columnas

In [ ]:
#importamos Pandas
import pandas as pd

## Series
### Creación de una serie a partir de una lista

• Series(data=lista, index=indices, dtype=tipo)

In [ ]:

s = pd.Series(['Matemáticas', 'Historia', 'Economía', 'Programación', 'Inglés'], name='Asignaturas',dtype='string')
print(s)

0     Matemáticas
1        Historia
2        Economía
3    Programación
4          Inglés
Name: Asignaturas, dtype: string

## Atributos de una serie
Existen varias propiedades o métodos para ver las características de una serie.

• s.size : Devuelve el número de elementos de la serie s.

• s.index : Devuelve una lista con los nombres de las filas de la serie.

• s.dtype : Devuelve el tipo de datos de los elementos de la serie s.

• s.name : Devuelve el nombre de la serie.

• s.values: Devuelve los elementos de la serie s.

In [ ]:
print(s.index.tolist())

[0, 1, 2, 3, 4]

In [ ]:
s.size

5

In [ ]:
s.name

'Asignaturas'

In [ ]:
s.values.tolist()

['Matemáticas', 'Historia', 'Economía', 'Programación', 'Inglés']

## Series desde un diccionario
• Series(data=diccionario, index=indices)

In [ ]:
s = pd.Series({'Matemáticas': 6.0,'Economía': 4.5, 'Programación': 8.5})
print(s)

Matemáticas     6.0
Economía        4.5
Programación    8.5
dtype: float64

In [ ]:
s.size

3

In [ ]:
s.index.tolist()

['Matemáticas', 'Economía', 'Programación']

In [ ]:
s.dtype

dtype('float64')

In [ ]:
print(s.values)

[ 1.  2.  3. nan]

In [ ]:
import numpy as np
s=pd.Series([1,2,3, np.nan ])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [ ]:
print(s.count())

3

In [ ]:
print(s.sum())

6.0

In [ ]:
s.cumsum()

0    1.0
1    3.0
2    6.0
3    NaN
dtype: float64

In [ ]:
s.max()

3.0

In [ ]:
s.idxmax()

2

In [ ]:
s.min()

1.0

In [ ]:
s.idxmin()

0

In [ ]:
s.mean()

np.float64(2.0)

In [ ]:
s.std()

1.0

In [ ]:
s.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

## DataFrame
Un objeto del tipo DataFrame define un conjunto de datos estructurado en forma de tabla donde cada columna es un objeto de tipo Series, es decir, todos los datos de una misma columna son del mismo tipo, y las filas son registros que pueden contender datos de distintos tipos.
Un DataFrame contiene dos índices, uno para las filas y otro para las columnas.

In [ ]:
#Creación de un DataFrame a partir de un diccionario de listas
#DataFrame(data=diccionario, index=filas, columns=columnas, dtype=tipos)
datos = {'nombre':['María', 'Luis', 'Carmen', 'Antonio'],'edad':[18, 22, 20, 21],'grado':['Economía', 'Medicina', 'Arquitectura', 'Economía'], 'correo':['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com', 'antonio@gmail.com']}
df = pd.DataFrame(datos)
df

    nombre  edad         grado             correo
0    María    18      Economía    maria@gmail.com
1     Luis    22      Medicina      luis@yahoo.es
2   Carmen    20  Arquitectura   carmen@gmail.com
3  Antonio    21      Economía  antonio@gmail.com

In [ ]:
#Creación de un DataFrame a partir de una lista de listas
#DataFrame(data=listas, index=filas, columns=columnas, dtype=tipos)
df = pd.DataFrame([['María', 18], ['Luis', 22], ['Carmen', 20]],columns=['Nombre', 'Edad'])
df

   Nombre  Edad
0   María    18
1    Luis    22
2  Carmen    20

In [ ]:
#Creación de un DataFrame a partir de una lista de diccionarios
#DataFrame(data=diccionarios, index=filas, columns=columnas, dtype=tipos)
df = pd.DataFrame([{'Nombre':'María', 'Edad':18}, {'Nombre':'Luis','Edad':22}, {'Nombre':'Carmen'}])
print(df)

   Nombre  Edad
0   María  18.0
1    Luis  22.0
2  Carmen   NaN

In [ ]:
#Creación de un DataFrame a partir de un array
#DataFrame(data=array, index=filas, columns=columnas, dtype=tipo)
df = pd.DataFrame(np.random.randn(4, 3), columns=['a', 'b', 'c'])
df

          a         b         c
0  0.444732  2.213759 -0.538161
1 -0.401343  0.837053  0.361796
2  2.160444 -0.512563 -1.195155
3 -1.063236  1.315221 -0.268300

In [ ]:
#Creación de un DataFrame a partir de un fichero CSV o Excel
#read_csv(fichero.csv, sep=separador, header=n, index_col=m, na_values=no-validos, decimal=separador-decimal)
df = pd.read_csv('https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv', sep=';', decimal=',')
df

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

## Propiedades
Existen varias propiedades o métodos para ver las características de un DataFrame.

• df.shape : Devuelve una tupla con el número de filas y columnas del DataFrame df.

• df.size : Devuelve el número de elementos del DataFrame.

• df.columns : Devuelve una lista con los nombres de las columnas del DataFrame df.

• df.index : Devuelve una lista con los nombres de las filas del DataFrame df.

• df.dtypes : Devuelve una serie con los tipos de datos de las columnas del df.

In [ ]:
df.shape

(14, 6)

In [ ]:
num_filas=df.shape[0]
num_cols=df.shape[1]
print(f'El DataFrame tiene {num_filas} filas y {num_cols} columnas')

El DataFrame tiene 14 filas y 6 columnas

In [ ]:
df.size

84

In [ ]:
df.columns

Index(['nombre', 'edad', 'sexo', 'peso', 'altura', 'colesterol'], dtype='object')

In [ ]:
df.index.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [ ]:
df.dtypes

nombre         object
edad            int64
sexo           object
peso          float64
altura        float64
colesterol    float64
dtype: object

### EDA
• df.head(n) : Devuelve las n primeras filas del DataFrame df.

• df.tail(n) : Devuelve las n últimas filas del DataFrame df.

• df.info() : Devuelve información (número de filas, número de columnas, índices, tipo de las columnas y memoria usado) sobre el DataFrame df.

• df.describe(include='all') : Genera estadísticas descriptivas de las columnas. Para columnas numéricas, incluye conteo, media, desviación estándar, valores mínimos y máximos, y cuartiles. Con include='all', también proporciona estadísticas para columnas categóricas como el conteo, el número de valores únicos, el valor más frecuente (top) y su frecuencia (freq).

• df.value_counts() : es un método de Series que devuelve una Serie que contiene el conteo de valores únicos en la columna, en orden descendente por defecto.

In [ ]:
df.head(3)

                         nombre  edad sexo  peso  altura  colesterol
0  José Luis Martínez Izquierdo    18    H  85.0    1.79       182.0
1                Rosa Díaz Díaz    32    M  65.0    1.73       232.0
2         Javier García Sánchez    24    H   NaN    1.81       191.0

In [ ]:
df.tail(3)

                             nombre  edad sexo   peso  altura  colesterol
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nombre      14 non-null     object
 1   edad        14 non-null     int64
 2   sexo        14 non-null     object
 3   peso        13 non-null     float64
 4   altura      14 non-null     float64
 5   colesterol  13 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 804.0+ bytes

In [ ]:
df.describe()

            edad        peso     altura  colesterol
count  14.000000   13.000000  14.000000   13.000000
mean   38.214286   70.923077   1.768571  220.230769
std    15.621379   16.126901   0.115016   39.847948
min    18.000000   51.000000   1.580000  148.000000
25%    24.750000   61.000000   1.705000  194.000000
50%    35.000000   65.000000   1.755000  210.000000
75%    49.750000   78.000000   1.840000  249.000000
max    68.000000  109.000000   1.980000  280.000000

In [ ]:
df['sexo'].value_counts()

sexo
H    8
M    6
Name: count, dtype: int64

### Renombrar los nombres de las filas y columnas

In [ ]:
#df.rename(columns=columnas, index=filas)

print(df.rename(columns={'nombre':'nombre y apellidos', 'altura':'estatura'}, index={0:1000, 1:1001, 2:1002}))

                   nombre y apellidos  edad sexo   peso  estatura  colesterol
1000     José Luis Martínez Izquierdo    18    H   85.0      1.79       182.0
1001                   Rosa Díaz Díaz    32    M   65.0      1.73       232.0
1002            Javier García Sánchez    24    H    NaN      1.81       191.0
3                 Carmen López Pinzón    35    M   65.0      1.70       200.0
4                Marisa López Collado    46    M   51.0      1.58       148.0
5                   Antonio Ruiz Cruz    68    H   66.0      1.74       249.0
6             Antonio Fernández Ocaña    51    H   62.0      1.72       276.0
7               Pilar Martín González    22    M   60.0      1.66         NaN
8                Pedro Gálvez Tenorio    35    H   90.0      1.94       241.0
9             Santiago Reillo Manzano    46    H   75.0      1.85       280.0
10              Macarena Álvarez Luna    53    M   55.0      1.62       262.0
11         José María de la Guía Sanz    58    H   78.0      1.87       198.0
12    Miguel Angel Cuadrado Gutiérrez    27    H  109.0      1.98       210.0
13              Carolina Rubio Moreno    20    M   61.0      1.77       194.0

### Accesos mediante posiciones

• df.iloc[i, j] : Devuelve el elemento que se encuentra en la fila i y la columna j del DataFrame df. Pueden indicarse secuencias de índices para obtener partes del DataFrame.

• df.iloc[filas, columnas] : Devuelve un DataFrame con los elementos de las filas de la lista filas y de las columnas de la lista columnas.

• df.iloc[i] : Devuelve una serie con los elementos de la fila i del DataFrame df.

In [ ]:
#segunda fila, tercera columna
print(df.iloc[1, 3])

65.0

In [ ]:
#segunda fila, columnas 0 y 1
print(df.iloc[1, :2])

nombre    Rosa Díaz Díaz
edad                  32
Name: 1, dtype: object

In [ ]:
#seleccion de la columna 0
print(df.iloc[:,0])

0        José Luis Martínez Izquierdo
1                      Rosa Díaz Díaz
2               Javier García Sánchez
3                 Carmen López Pinzón
4                Marisa López Collado
5                   Antonio Ruiz Cruz
6             Antonio Fernández Ocaña
7               Pilar Martín González
8                Pedro Gálvez Tenorio
9             Santiago Reillo Manzano
10              Macarena Álvarez Luna
11         José María de la Guía Sanz
12    Miguel Angel Cuadrado Gutiérrez
13              Carolina Rubio Moreno
Name: nombre, dtype: object

### Acceso a los elementos mediante nombres
• df.loc[fila, columna] : Devuelve el elemento que se encuentra en la fila con nombre fila y la columna de con nombre columna del DataFrame df.

• df.loc[filas, columnas] : Devuelve un DataFrame con los elemento que se encuentra en las filas con los nombres de la lista filas y las columnas con los nombres de la lista columnas del DataFrame df.

• df[columna] : Devuelve una serie con los elementos de la columna de nombre columna del DataFrame df.

• df.columna : Devuelve una serie con los elementos de la columna de nombre columna del DataFrame df. Es similar al método anterior pero solo funciona cuando el nombre de la columna no tiene espacios en blanco.

In [ ]:
#fila 2, columna 'colesterol'
print(df.loc[2, 'colesterol'])

191.0

In [ ]:
#filas 0,1,2 y 3 columnas 'colesterol' y 'peso'
#el índice final (en este caso, 3) es inclusivo.
print(df.loc[:3, ('colesterol','peso')])

   colesterol  peso
0       182.0  85.0
1       232.0  65.0
2       191.0   NaN
3       200.0  65.0

In [ ]:
print(df['colesterol'])

0     182.0
1     232.0
2     191.0
3     200.0
4     148.0
5     249.0
6     276.0
7       NaN
8     241.0
9     280.0
10    262.0
11    198.0
12    210.0
13    194.0
Name: colesterol, dtype: float64

In [ ]:
df.colesterol

0     182.0
1     232.0
2     191.0
3     200.0
4     148.0
5     249.0
6     276.0
7       NaN
8     241.0
9     280.0
10    262.0
11    198.0
12    210.0
13    194.0
Name: colesterol, dtype: float64

### Operaciones con las columnas de un DataFrame
#### Añadir columnas a un DataFrame
• d[nombre] = lista: Añade al DataFrame df una nueva columna con el nombre nombre y los valores de la lista lista. La lista debe tener el mismo tamaño que el número de filas de df.

• d[nombre] = serie: Añade al DataFrame df una nueva columna con el nombre nombre y los valores de la serie serie. Si el tamaño de la serie es menor que el número de filas de df se rellena con valores NaN mientras que si es mayor se recorta.

In [ ]:
df['diabetes'] = pd.Series([False, False, True, False, True])
df

,nombre,edad,sexo,peso,altura,colesterol,diabetes
0,José Luis Martínez Izquierdo,18,H,85.0,1.79,182.0,False
1,Rosa Díaz Díaz,32,M,65.0,1.73,232.0,False
2,Javier García Sánchez,24,H,NaN,1.81,191.0,True
3,Carmen López Pinzón,35,M,65.0,1.70,200.0,False
4,Marisa López Collado,46,M,51.0,1.58,148.0,True
5,Antonio Ruiz Cruz,68,H,66.0,1.74,249.0,NaN
6,Antonio Fernández Ocaña,51,H,62.0,1.72,276.0,NaN
7,Pilar Martín González,22,M,60.0,1.66,NaN,NaN
8,Pedro Gálvez Tenorio,35,H,90.0,1.94,241.0,NaN
9,Santiago Reillo Manzano,46,H,75.0,1.85,280.0,NaN
10,Macarena Álvarez Luna,53,M,55.0,1.62,262.0,NaN
11,José María de la Guía Sanz,58,H,78.0,1.87,198.0,NaN
12,Miguel Angel Cuadrado Gutiérrez,27,H,109.0,1.98,210.0,NaN
13,Carolina Rubio Moreno,20,M,61.0,1.77,194.0,NaN

### Operaciones sobre columnas

In [ ]:
print(df['altura']*100)

0     179.0
1     173.0
2     181.0
3     170.0
4     158.0
5     174.0
6     172.0
7     166.0
8     194.0
9     185.0
10    162.0
11    187.0
12    198.0
13    177.0
Name: altura, dtype: float64

In [ ]:
print(df['sexo']=='M')

0     False
1      True
2     False
3      True
4      True
5     False
6     False
7      True
8     False
9     False
10     True
11    False
12    False
13     True
Name: sexo, dtype: bool

### Aplicar funciones a columnas

In [ ]:
df['nombre'] = df['nombre'].apply(str.upper)
df

,nombre,edad,sexo,peso,altura,colesterol,diabetes
0,JOSÉ LUIS MARTÍNEZ IZQUIERDO,18,H,85.0,1.79,182.0,False
1,ROSA DÍAZ DÍAZ,32,M,65.0,1.73,232.0,False
2,JAVIER GARCÍA SÁNCHEZ,24,H,NaN,1.81,191.0,True
3,CARMEN LÓPEZ PINZÓN,35,M,65.0,1.70,200.0,False
4,MARISA LÓPEZ COLLADO,46,M,51.0,1.58,148.0,True
5,ANTONIO RUIZ CRUZ,68,H,66.0,1.74,249.0,NaN
6,ANTONIO FERNÁNDEZ OCAÑA,51,H,62.0,1.72,276.0,NaN
7,PILAR MARTÍN GONZÁLEZ,22,M,60.0,1.66,NaN,NaN
8,PEDRO GÁLVEZ TENORIO,35,H,90.0,1.94,241.0,NaN
9,SANTIAGO REILLO MANZANO,46,H,75.0,1.85,280.0,NaN
10,MACARENA ÁLVAREZ LUNA,53,M,55.0,1.62,262.0,NaN
11,JOSÉ MARÍA DE LA GUÍA SANZ,58,H,78.0,1.87,198.0,NaN
12,MIGUEL ANGEL CUADRADO GUTIÉRREZ,27,H,109.0,1.98,210.0,NaN
13,CAROLINA RUBIO MORENO,20,M,61.0,1.77,194.0,NaN

In [ ]:
# Clasificar edades
df['categoria'] = df['edad'].apply(lambda x: 'mayor' if x >= 18 else 'menor')
df

,nombre,edad,sexo,peso,altura,colesterol,diabetes,categoria
0,JOSÉ LUIS MARTÍNEZ IZQUIERDO,18,H,85.0,1.79,182.0,False,mayor
1,ROSA DÍAZ DÍAZ,32,M,65.0,1.73,232.0,False,mayor
2,JAVIER GARCÍA SÁNCHEZ,24,H,NaN,1.81,191.0,True,mayor
3,CARMEN LÓPEZ PINZÓN,35,M,65.0,1.70,200.0,False,mayor
4,MARISA LÓPEZ COLLADO,46,M,51.0,1.58,148.0,True,mayor
5,ANTONIO RUIZ CRUZ,68,H,66.0,1.74,249.0,NaN,mayor
6,ANTONIO FERNÁNDEZ OCAÑA,51,H,62.0,1.72,276.0,NaN,mayor
7,PILAR MARTÍN GONZÁLEZ,22,M,60.0,1.66,NaN,NaN,mayor
8,PEDRO GÁLVEZ TENORIO,35,H,90.0,1.94,241.0,NaN,mayor
9,SANTIAGO REILLO MANZANO,46,H,75.0,1.85,280.0,NaN,mayor
10,MACARENA ÁLVAREZ LUNA,53,M,55.0,1.62,262.0,NaN,mayor
11,JOSÉ MARÍA DE LA GUÍA SANZ,58,H,78.0,1.87,198.0,NaN,mayor
12,MIGUEL ANGEL CUADRADO GUTIÉRREZ,27,H,109.0,1.98,210.0,NaN,mayor
13,CAROLINA RUBIO MORENO,20,M,61.0,1.77,194.0,NaN,mayor

In [ ]:
df['categoria_colesterol'] = df['colesterol'].apply(
    lambda x: 'sin dato' if pd.isna(x)
    else ('alto' if x >= 240 else ('normal' if x >= 200 else 'bajo'))
)
df

,nombre,edad,sexo,peso,altura,colesterol,categoria,categoria_colesterol
0,JOSÉ LUIS MARTÍNEZ IZQUIERDO,18,H,85.0,1.79,182.0,mayor,bajo
1,ROSA DÍAZ DÍAZ,32,M,65.0,1.73,232.0,mayor,normal
2,JAVIER GARCÍA SÁNCHEZ,24,H,NaN,1.81,191.0,mayor,bajo
3,CARMEN LÓPEZ PINZÓN,35,M,65.0,1.70,200.0,mayor,normal
4,MARISA LÓPEZ COLLADO,46,M,51.0,1.58,148.0,mayor,bajo
5,ANTONIO RUIZ CRUZ,68,H,66.0,1.74,249.0,mayor,alto
6,ANTONIO FERNÁNDEZ OCAÑA,51,H,62.0,1.72,276.0,mayor,alto
7,PILAR MARTÍN GONZÁLEZ,22,M,60.0,1.66,NaN,mayor,sin dato
8,PEDRO GÁLVEZ TENORIO,35,H,90.0,1.94,241.0,mayor,alto
9,SANTIAGO REILLO MANZANO,46,H,75.0,1.85,280.0,mayor,alto
10,MACARENA ÁLVAREZ LUNA,53,M,55.0,1.62,262.0,mayor,alto
11,JOSÉ MARÍA DE LA GUÍA SANZ,58,H,78.0,1.87,198.0,mayor,bajo
12,MIGUEL ANGEL CUADRADO GUTIÉRREZ,27,H,109.0,1.98,210.0,mayor,normal
13,CAROLINA RUBIO MORENO,20,M,61.0,1.77,194.0,mayor,bajo

### **¡Evita el .apply(lambda...) siempre que puedas!**
### pd.cut
agrupar números en "bins" (categorías):
Bins: Define los límites.

Labels: Los nombres de las categorías.

Right=False: Maneja si el límite superior se incluye o no

### **¡Evita el .apply(lambda...) siempre que puedas!**
### `pd.cut`

`pd.cut` es una función fundamental en Pandas que se utiliza para **segmentar y ordenar valores de datos en discretos 'bins' (intervalos)**. Es ideal para transformar datos numéricos continuos en categorías ordinales o agrupar datos en rangos específicos, siendo más eficiente y legible que `apply(lambda x: ...) ` para esta tarea.

**Sintaxis:**
`pd.cut(x, bins, right=True, labels=None, include_lowest=False)`

**Parámetros clave:**

* x: serie

* Bins: Define los límites.

* Labels: Los nombres de las categorías.

* Right=False: Maneja si el límite superior se incluye o no.

In [ ]:
# El primer rango es de 0 a 200 (bajo), 200 a 240 (normal), 240 a infinito (alto)
bins = [0, 200, 240, float('inf')]
labels = ['bajo', 'normal', 'alto']
# right=False hace que el intervalo sea [200, 240), es decir, incluye el 200 pero no el 240
df['categoria_colesterol'] = pd.cut(df['colesterol'], bins=bins, labels=labels, right=False)

### Convertir una columna al tipo datetime
to_datetime(columna, formato)

In [ ]:
df1 = pd.DataFrame({'Name': ['María', 'Carlos', 'Carmen'], 'Nacimiento':['05-03-2000', '20-05-2001', '10-12-1999']})
df1

     Name  Nacimiento
0   María  05-03-2000
1  Carlos  20-05-2001
2  Carmen  10-12-1999

In [ ]:
print(f'Tipos de datos:\n{df1.dtypes}')

Tipos de datos:
Name          object
Nacimiento    object
dtype: object

In [ ]:
df1['Nacimiento'] = pd.to_datetime(df1.Nacimiento, format = '%d-%m-%Y')
print(df1)

     Name Nacimiento
0   María 2000-03-05
1  Carlos 2001-05-20
2  Carmen 1999-12-10

In [ ]:
print(f'Tipos de datos:\n{df1.dtypes}')

Tipos de datos:
Name                  object
Nacimiento    datetime64[ns]
dtype: object

### Resumir la información de un DataFrame
por columnas:

• df.count() : Devuelve una serie número de elementos que no son nulos ni NaN en cada columna del DataFrame df.

• df.sum() : Devuelve una serie con la suma de los datos de las columnas del DataFrame df cuando los datos son de un tipo numérico, o la concatenación de ellos cuando son del tipo cadena str.

• df.cumsum() : Devuelve un DataFrame con la suma acumulada de los datos de las columnas del DataFrame df cuando los datos son de un tipo numérico.

• df.min() : Devuelve una serie con los menores de los datos de las columnas del DataFrame df.

• df.max() : Devuelve una serie con los mayores de los datos de las columnas del DataFrame df.

• df.mean() : Devuelve una serie con las media de los datos de las columnas del DataFrame df cuando los datos son de un tipo numérico.

• df.std() : Devuelve una serie con las desviaciones típicas de los datos de las columnas del DataFrame df cuando los datos son de un tipo numérico.

• df.describe(include = tipo) : Devuelve un DataFrame con un resumen estadístico de las columnas del DataFrame df del tipo tipo. Para los datos numéricos (number) se calcula la media, la desviación típica, el mínimo, el máximo y los cuartiles de las columnas numéricas. Para los datos no numéricos (object) se calcula el número de valores, el número de valores distin‑
tos, la moda y su frecuencia. Si no se indica el tipo solo se consideran las columnas numéricas.

In [ ]:
df.describe()

            edad        peso     altura  colesterol
count  14.000000   13.000000  14.000000   13.000000
mean   38.214286   70.923077   1.768571  220.230769
std    15.621379   16.126901   0.115016   39.847948
min    18.000000   51.000000   1.580000  148.000000
25%    24.750000   61.000000   1.705000  194.000000
50%    35.000000   65.000000   1.755000  210.000000
75%    49.750000   78.000000   1.840000  249.000000
max    68.000000  109.000000   1.980000  280.000000

In [ ]:
print(df.describe(include='object'))

                              nombre sexo diabetes categoria
count                             14   14        5        14
unique                            14    2        2         1
top     JOSÉ LUIS MARTÍNEZ IZQUIERDO    H    False     mayor
freq                               1    8        3        14

### Eliminar columnas de un DataFrame
• del d[nombre] : Elimina la columna con nombre nombre del DataFrame df.

• df.pop(nombre) : Elimina la columna con nombre nombre del DataFrame df y la devuelve como una serie.

In [ ]:
edad = df.pop('edad')
print(df)

                             nombre sexo   peso  altura  colesterol diabetes  \
0      JOSÉ LUIS MARTÍNEZ IZQUIERDO    H   85.0    1.79       182.0    False
1                    ROSA DÍAZ DÍAZ    M   65.0    1.73       232.0    False
2             JAVIER GARCÍA SÁNCHEZ    H    NaN    1.81       191.0     True
3               CARMEN LÓPEZ PINZÓN    M   65.0    1.70       200.0    False
4              MARISA LÓPEZ COLLADO    M   51.0    1.58       148.0     True
5                 ANTONIO RUIZ CRUZ    H   66.0    1.74       249.0      NaN
6           ANTONIO FERNÁNDEZ OCAÑA    H   62.0    1.72       276.0      NaN
7             PILAR MARTÍN GONZÁLEZ    M   60.0    1.66         NaN      NaN
8              PEDRO GÁLVEZ TENORIO    H   90.0    1.94       241.0      NaN
9           SANTIAGO REILLO MANZANO    H   75.0    1.85       280.0      NaN
10            MACARENA ÁLVAREZ LUNA    M   55.0    1.62       262.0      NaN
11       JOSÉ MARÍA DE LA GUÍA SANZ    H   78.0    1.87       198.0      NaN
12  MIGUEL ANGEL CUADRADO GUTIÉRREZ    H  109.0    1.98       210.0      NaN
13            CAROLINA RUBIO MORENO    M   61.0    1.77       194.0      NaN

   categoria
0      mayor
1      mayor
2      mayor
3      mayor
4      mayor
5      mayor
6      mayor
7      mayor
8      mayor
9      mayor
10     mayor
11     mayor
12     mayor
13     mayor

In [ ]:
print(edad)

0     18
1     32
2     24
3     35
4     46
5     68
6     51
7     22
8     35
9     46
10    53
11    58
12    27
13    20
Name: edad, dtype: int64

In [ ]:
df_temp = df.copy()
del df_temp['edad']
df_temp #modifica el df

                             nombre sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    M   65.0    1.73       232.0
2             Javier García Sánchez    H    NaN    1.81       191.0
3               Carmen López Pinzón    M   65.0    1.70       200.0
4              Marisa López Collado    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    H   62.0    1.72       276.0
7             Pilar Martín González    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    M   55.0    1.62       262.0
11       José María de la Guía Sanz    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    M   61.0    1.77       194.0

### Operaciones con las filas de un DataFrame
#### Añadir una fila a un DataFrame
• pd.concat(df,serie, ignore_index=True) : Devuelve el DataFrame que resulta de añadir nuevas filas.

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv', sep=';', decimal=',')
nueva_fila =  pd.Series(['Carlos Rivas', 28, 'H', 89.0, 1.78,245.0], index=['nombre','edad','sexo','peso','altura','colesterol'])
nueva_fila_df=nueva_fila.to_frame().T   #Convertimos a df
df=pd.concat([df,nueva_fila_df], ignore_index=True)
df

                             nombre edad sexo   peso altura colesterol
0      José Luis Martínez Izquierdo   18    H   85.0   1.79      182.0
1                    Rosa Díaz Díaz   32    M   65.0   1.73      232.0
2             Javier García Sánchez   24    H    NaN   1.81      191.0
3               Carmen López Pinzón   35    M   65.0    1.7      200.0
4              Marisa López Collado   46    M   51.0   1.58      148.0
5                 Antonio Ruiz Cruz   68    H   66.0   1.74      249.0
6           Antonio Fernández Ocaña   51    H   62.0   1.72      276.0
7             Pilar Martín González   22    M   60.0   1.66        NaN
8              Pedro Gálvez Tenorio   35    H   90.0   1.94      241.0
9           Santiago Reillo Manzano   46    H   75.0   1.85      280.0
10            Macarena Álvarez Luna   53    M   55.0   1.62      262.0
11       José María de la Guía Sanz   58    H   78.0   1.87      198.0
12  Miguel Angel Cuadrado Gutiérrez   27    H  109.0   1.98      210.0
13            Carolina Rubio Moreno   20    M   61.0   1.77      194.0
14                     Carlos Rivas   28    H   89.0   1.78      245.0

### Explicación de `df.drop()`

El método `df.drop()` se utiliza para **eliminar filas o columnas** de un DataFrame. Es importante recordar que, por defecto, `drop()` devuelve una *copia* del DataFrame con los elementos eliminados, no modifica el DataFrame original a menos que se use el parámetro `inplace=True`.

**Parámetros clave:**

*   **`labels`**: Corresponde al nombre(s) de la fila(s) o columna(s) que deseas eliminar. Puede ser una etiqueta única o una lista de etiquetas.
*   **`axis`**: Especifica si se eliminan filas o columnas:
    *   `axis=0` (o `axis='index'`) para eliminar filas (es el valor por defecto).
    *   `axis=1` (o `axis='columns'`) para eliminar columnas.
*   **`inplace`**: Un valor booleano (`True` o `False`). Si es `True`, la operación se realiza directamente sobre el DataFrame original y no devuelve nada. Si es `False` (por defecto), devuelve un nuevo DataFrame con los elementos eliminados y el original permanece sin cambios.
*   **`errors`**: Puede ser `'ignore'` o `'raise'` (por defecto). Si es `'ignore'`, suprime los errores si alguna de las etiquetas especificadas no se encuentra. Si es `'raise'`, lanzará un error si una etiqueta no existe.

In [ ]:
print('DataFrame original:')
print(df)

# Eliminar una sola fila por su índice (axis=0 es el valor por defecto)
# Esto devuelve una copia del DataFrame sin la fila 0
df_sin_fila_0 = df.drop(0)
print('\nDataFrame sin la fila 0:')
print(df_sin_fila_0.head())

# Eliminar múltiples filas por sus índices
df_sin_filas_1_y_3 = df.drop([1, 3])
print('\nDataFrame sin las filas 1 y 3:')
print(df_sin_filas_1_y_3.head())

# Eliminar una columna (usando axis=1)
df_sin_columna_sexo = df.drop('sexo', axis=1)
print("\nDataFrame sin la columna 'sexo':")
print(df_sin_columna_sexo.head())

# Eliminar múltiples columnas
df_sin_peso_y_altura = df.drop(['peso', 'altura'], axis=1)
print("\nDataFrame sin las columnas 'peso' y 'altura':")
print(df_sin_peso_y_altura.head())

# Eliminar filas modificando el DataFrame original (inplace=True)
# Ten cuidado con inplace=True, ya que modifica el DataFrame directamente.

df = pd.read_csv('https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv', sep=';', decimal=',')

nueva_fila = pd.Series(['Carlos Rivas', 28, 'H', 89.0, 1.78, 245.0], index=['nombre','edad','sexo','peso','altura','colesterol'])
df = pd.concat([df, nueva_fila.to_frame().T], ignore_index=True)

print('\nDataFrame original antes de inplace=True:')
print(df.tail())

df.drop(14, inplace=True) # Eliminar la última fila (Carlos Rivas)
print('\nDataFrame después de eliminar la fila 14 con inplace=True:')
print(df.tail())

DataFrame original:
                             nombre edad sexo   peso altura colesterol
0      José Luis Martínez Izquierdo   18    H   85.0   1.79      182.0
1                    Rosa Díaz Díaz   32    M   65.0   1.73      232.0
2             Javier García Sánchez   24    H    NaN   1.81      191.0
3               Carmen López Pinzón   35    M   65.0    1.7      200.0
4              Marisa López Collado   46    M   51.0   1.58      148.0
5                 Antonio Ruiz Cruz   68    H   66.0   1.74      249.0
6           Antonio Fernández Ocaña   51    H   62.0   1.72      276.0
7             Pilar Martín González   22    M   60.0   1.66        NaN
8              Pedro Gálvez Tenorio   35    H   90.0   1.94      241.0
9           Santiago Reillo Manzano   46    H   75.0   1.85      280.0
10            Macarena Álvarez Luna   53    M   55.0   1.62      262.0
11       José María de la Guía Sanz   58    H   78.0   1.87      198.0
12  Miguel Angel Cuadrado Gutiérrez   27    H  109.0   1.98      210.0
13            Carolina Rubio Moreno   20    M   61.0   1.77      194.0
14                     Carlos Rivas   28    H   89.0   1.78      245.0

DataFrame sin la fila 0:
                  nombre edad sexo  peso altura colesterol
1         Rosa Díaz Díaz   32    M  65.0   1.73      232.0
2  Javier García Sánchez   24    H   NaN   1.81      191.0
3    Carmen López Pinzón   35    M  65.0    1.7      200.0
4   Marisa López Collado   46    M  51.0   1.58      148.0
5      Antonio Ruiz Cruz   68    H  66.0   1.74      249.0

DataFrame sin las filas 1 y 3:
                         nombre edad sexo  peso altura colesterol
0  José Luis Martínez Izquierdo   18    H  85.0   1.79      182.0
2         Javier García Sánchez   24    H   NaN   1.81      191.0
4          Marisa López Collado   46    M  51.0   1.58      148.0
5             Antonio Ruiz Cruz   68    H  66.0   1.74      249.0
6       Antonio Fernández Ocaña   51    H  62.0   1.72      276.0

DataFrame sin la columna 'sexo':
                         nombre edad  peso altura colesterol
0  José Luis Martínez Izquierdo   18  85.0   1.79      182.0
1                Rosa Díaz Díaz   32  65.0   1.73      232.0
2         Javier García Sánchez   24   NaN   1.81      191.0
3           Carmen López Pinzón   35  65.0    1.7      200.0
4          Marisa López Collado   46  51.0   1.58      148.0

DataFrame sin las columnas 'peso' y 'altura':
                         nombre edad sexo colesterol
0  José Luis Martínez Izquierdo   18    H      182.0
1                Rosa Díaz Díaz   32    M      232.0
2         Javier García Sánchez   24    H      191.0
3           Carmen López Pinzón   35    M      200.0
4          Marisa López Collado   46    M      148.0

DataFrame original antes de inplace=True:
                             nombre edad sexo   peso altura colesterol
10            Macarena Álvarez Luna   53    M   55.0   1.62      262.0
11       José María de la Guía Sanz   58    H   78.0   1.87      198.0
12  Miguel Angel Cuadrado Gutiérrez   27    H  109.0   1.98      210.0
13            Carolina Rubio Moreno   20    M   61.0   1.77      194.0
14                     Carlos Rivas   28    H   89.0   1.78      245.0

DataFrame después de eliminar la fila 14 con inplace=True:
                             nombre edad sexo   peso altura colesterol
9           Santiago Reillo Manzano   46    H   75.0   1.85      280.0
10            Macarena Álvarez Luna   53    M   55.0   1.62      262.0
11       José María de la Guía Sanz   58    H   78.0   1.87      198.0
12  Miguel Angel Cuadrado Gutiérrez   27    H  109.0   1.98      210.0
13            Carolina Rubio Moreno   20    M   61.0   1.77      194.0

### Filtrado de las filas de un DataFrame
• df[condicion] : Devuelve un DataFrame con las filas del DataFrame df que se corresponden
con el valor True de la lista booleana condicion.

In [ ]:
print(df[(df['sexo']=='H') & (df['colesterol'] > 260)])

                    nombre edad sexo  peso altura colesterol
6  Antonio Fernández Ocaña   51    H  62.0   1.72      276.0
9  Santiago Reillo Manzano   46    H  75.0   1.85      280.0

### Ordenar un DataFrame
Para ordenar un DataFrame de acuerdo a los valores de una determinada columna se utilizan los si‑
guientes métodos:
• df.sort_values(columna, ascending=booleano) : Devuelve el DataFrame que resulta
de ordenar las filas del DataFrame df según los valores del la columna con nombre columna. Si
argumento del parámetro ascending es True el orden es creciente y si es False decreciente.
• df.sort_index(ascending=booleano) : Devuelve el DataFrame que resulta de ordenar
las filas del DataFrame df según los nombres de las filas. Si el argumento del parámetro
ascending es True el orden es creciente y si es False decreciente.

In [ ]:
print(df.sort_values('colesterol'))

                             nombre edad sexo   peso altura colesterol
4              Marisa López Collado   46    M   51.0   1.58      148.0
0      José Luis Martínez Izquierdo   18    H   85.0   1.79      182.0
2             Javier García Sánchez   24    H    NaN   1.81      191.0
13            Carolina Rubio Moreno   20    M   61.0   1.77      194.0
11       José María de la Guía Sanz   58    H   78.0   1.87      198.0
3               Carmen López Pinzón   35    M   65.0    1.7      200.0
12  Miguel Angel Cuadrado Gutiérrez   27    H  109.0   1.98      210.0
1                    Rosa Díaz Díaz   32    M   65.0   1.73      232.0
8              Pedro Gálvez Tenorio   35    H   90.0   1.94      241.0
5                 Antonio Ruiz Cruz   68    H   66.0   1.74      249.0
10            Macarena Álvarez Luna   53    M   55.0   1.62      262.0
6           Antonio Fernández Ocaña   51    H   62.0   1.72      276.0
9           Santiago Reillo Manzano   46    H   75.0   1.85      280.0
7             Pilar Martín González   22    M   60.0   1.66        NaN

### Eliminar las filas con datos desconocidos en un DataFrame
• s.dropna(subset=columnas) : Devuelve el DataFrame que resulta de eliminar las filas que
contienen algún dato desconocido o nulo en las columnas de la lista columna del DataFrame df.
Si no se pasa un argumento al parámetro subset se aplica a todas las columnas del DataFrame.

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv', sep=';', decimal=',')
print(df)

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
print(df.dropna())

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

## Filtrar Datos de un DataFrame


*   **`.query()` (Selección basada en expresiones de cadena):** Permite filtrar filas de un DataFrame utilizando una **expresión booleana en forma de cadena de texto**. A menudo es más legible que los filtros booleanos tradicionales con múltiples condiciones.

*   **`.isin()` (Filtrado por pertenencia a una lista):** Es un método de Series que devuelve un valor booleano indicando si cada elemento de la Serie **está contenido en los valores de una lista o Series pasadas como argumento**. Es muy útil para filtrar filas donde una columna toma uno de varios valores posibles.

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv', sep=';', decimal=',')

In [ ]:
# Personas con colesterol alto
df.query("colesterol >= 240")

                     nombre  edad sexo  peso  altura  colesterol
5         Antonio Ruiz Cruz    68    H  66.0    1.74       249.0
6   Antonio Fernández Ocaña    51    H  62.0    1.72       276.0
8      Pedro Gálvez Tenorio    35    H  90.0    1.94       241.0
9   Santiago Reillo Manzano    46    H  75.0    1.85       280.0
10    Macarena Álvarez Luna    53    M  55.0    1.62       262.0

In [ ]:
# Mujeres mayores de 30
df.query("sexo == 'M' and edad > 30")

                   nombre  edad sexo  peso  altura  colesterol
1          Rosa Díaz Díaz    32    M  65.0    1.73       232.0
3     Carmen López Pinzón    35    M  65.0    1.70       200.0
4    Marisa López Collado    46    M  51.0    1.58       148.0
10  Macarena Álvarez Luna    53    M  55.0    1.62       262.0

In [ ]:
# Altura mayor a 1.80 y peso conocido
df.query("altura > 1.80 and peso == peso")  # truco para excluir NaN

                             nombre  edad sexo   peso  altura  colesterol
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0

In [ ]:
# Personas con edades específicas
df[df['edad'].isin([20, 35, 46])]

                     nombre  edad sexo  peso  altura  colesterol
3       Carmen López Pinzón    35    M  65.0    1.70       200.0
4      Marisa López Collado    46    M  51.0    1.58       148.0
8      Pedro Gálvez Tenorio    35    H  90.0    1.94       241.0
9   Santiago Reillo Manzano    46    H  75.0    1.85       280.0
13    Carolina Rubio Moreno    20    M  61.0    1.77       194.0

In [ ]:
# Filtrar por nombres específicos
df[df['nombre'].isin(['Rosa Díaz Díaz', 'Pedro Gálvez Tenorio'])]

                 nombre  edad sexo  peso  altura  colesterol
1        Rosa Díaz Díaz    32    M  65.0    1.73       232.0
8  Pedro Gálvez Tenorio    35    H  90.0    1.94       241.0

In [ ]:
# Combinar: mujeres con edades específicas
df[(df['sexo'] == 'M') & (df['edad'].isin([20, 32, 35]))]

                   nombre  edad sexo  peso  altura  colesterol
1          Rosa Díaz Díaz    32    M  65.0    1.73       232.0
3     Carmen López Pinzón    35    M  65.0    1.70       200.0
13  Carolina Rubio Moreno    20    M  61.0    1.77       194.0

### Agrupación de un DataFrame
#### Para dividir un DataFrame en grupos se utiliza el siguiente método:
• df.groupby(columnas).groups : Devuelve un diccionario con cuyas claves son las tuplas
que resultan de todas las combinaciones de los valores de las columnas con nombres en la
lista columnas, y valores las listas de los nombres de las filas que contienen esos valores en las
correspondientes columnas del DataFrame df.

In [ ]:
print(df.groupby('sexo').groups)

{'H': [0, 2, 5, 6, 8, 9, 11, 12], 'M': [1, 3, 4, 7, 10, 13]}

In [ ]:
print(df.groupby(['sexo','edad']).groups)

{('H', 18): [0], ('H', 24): [2], ('H', 27): [12], ('H', 35): [8], ('H', 46): [9], ('H', 51): [6], ('H', 58): [11], ('H', 68): [5], ('M', 20): [13], ('M', 22): [7], ('M', 32): [1], ('M', 35): [3], ('M', 46): [4], ('M', 53): [10]}

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv', sep=';', decimal=',')

#### Para obtener un grupo concreto se utiliza el siguiente método:
• df.groupby(columnas).get_group(valores) : Devuelve un DataFrame con las filas del
DataFrame df que cumplen que las columnas de la lista columnas presentan los valores de la
tupla valores. La lista columnas y la tupla valores deben tener el mismo tamaño.

In [ ]:
print(df.groupby('sexo').get_group('M'))

                   nombre  edad sexo  peso  altura  colesterol
1          Rosa Díaz Díaz    32    M  65.0    1.73       232.0
3     Carmen López Pinzón    35    M  65.0    1.70       200.0
4    Marisa López Collado    46    M  51.0    1.58       148.0
7   Pilar Martín González    22    M  60.0    1.66         NaN
10  Macarena Álvarez Luna    53    M  55.0    1.62       262.0
13  Carolina Rubio Moreno    20    M  61.0    1.77       194.0

### Aplicar una función de agregación por grupos
Una vez dividido el DataFame en grupos, es posible aplicar funciones de agregación a cada grupo
mediante el siguiente método:

• `df.groupby(columnas).agg(funciones)` : Devuelve un DataFrame con el resultado de
aplicar las funciones de agregación de la lista `funciones` a cada uno de los DataFrames que
resultan de dividir el DataFrame según las `columnas` especificadas.

La función `agg` es muy flexible y puede recibir diferentes tipos de argumentos para `funciones`:

1.  **Una sola función:** Aplica la misma función a todas las columnas seleccionadas.
    *   Ejemplo: `df.groupby('sexo')[['edad', 'peso']].agg(np.mean)`

2.  **Una lista de funciones:** Aplica todas las funciones de la lista a cada columna seleccionada.
    *   Ejemplo: `df.groupby('sexo')[['edad', 'peso']].agg([np.mean, np.max])`

3.  **Un diccionario:** Permite especificar diferentes funciones o listas de funciones para columnas específicas.
    *   Ejemplo: `df.groupby('sexo').agg({'edad': 'mean', 'peso': ['min', 'max']})`

Las funciones de agregación pueden ser objetos de función (como `np.mean`, `np.min`, `len`) o sus nombres como cadenas de texto (como `'mean'`, `'min'`, `'count'`). Una función de agregación toma como argumento una serie de valores y devuelve un único valor.

Algunas de las funciones de agregación más comunes son:
• `np.min` (o `'min'`) : Devuelve el mínimo de una lista de valores.
• `np.max` (o `'max'`) : Devuelve el máximo de una lista de valores.
• `np.count_nonzero` (o `'count'`) : Devuelve el número de valores no nulos de una lista de valores.
• `np.sum` (o `'sum'`) : Devuelve la suma de una lista de valores.
• `np.mean` (o `'mean'`) : Devuelve la media de una lista de valores.
• `np.std` (o `'std'`) : Devuelve la desviación típica de una lista de valores.
• `len` (o `'size'`) : Devuelve el número total de elementos (incluyendo nulos).

In [ ]:
import numpy as np

# Ejemplo 1: Media de columnas numéricas agrupadas por 'sexo'
print('Media por sexo:')
display(df.groupby('sexo')[['edad', 'peso', 'altura', 'colesterol']].agg(np.mean))

# Ejemplo 2: Múltiples agregaciones para las mismas columnas
print('\nMínimo, máximo y media por sexo:')
display(df.groupby('sexo')[['edad', 'peso', 'altura', 'colesterol']].agg([np.min, np.max, np.mean]))

# Ejemplo 3: Agregaciones diferentes para columnas específicas usando un diccionario
print('\nAgregaciones personalizadas por sexo:')
display(df.groupby('sexo').agg({
    'edad': ['mean', 'min'],
    'peso': 'max',
    'altura': np.std,
    'colesterol': 'count' # Contar valores no nulos
}))

Media por sexo:

/tmp/ipykernel_103905/4140245673.py:5: FutureWarning: The provided callable <function mean at 0x7a877f3398a0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  display(df.groupby('sexo')[['edad', 'peso', 'altura', 'colesterol']].agg(np.mean))

           edad       peso    altura  colesterol
sexo
H     40.875000  80.714286  1.837500     228.375
M     34.666667  59.500000  1.676667     207.200

Mínimo, máximo y media por sexo:

/tmp/ipykernel_103905/4140245673.py:9: FutureWarning: The provided callable <function min at 0x7a877f338fe0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  display(df.groupby('sexo')[['edad', 'peso', 'altura', 'colesterol']].agg([np.min, np.max, np.mean]))
/tmp/ipykernel_103905/4140245673.py:9: FutureWarning: The provided callable <function max at 0x7a877f338ea0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  display(df.groupby('sexo')[['edad', 'peso', 'altura', 'colesterol']].agg([np.min, np.max, np.mean]))
/tmp/ipykernel_103905/4140245673.py:9: FutureWarning: The provided callable <function mean at 0x7a877f3398a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  display(df.groupby('sexo')[['edad', 'peso', 'altura', 'colesterol']].agg([np.min, np.max, np.mean]))
/tmp/ipykernel_103905/4140245673.py:9: FutureWarning: The provided callable <function min at 0x7a877f338fe0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  display(df.groupby('sexo')[['edad', 'peso', 'altura', 'colesterol']].agg([np.min, np.max, np.mean]))

     edad                 peso                   altura                  \
      min max       mean   min    max       mean    min   max      mean
sexo
H      18  68  40.875000  62.0  109.0  80.714286   1.72  1.98  1.837500
M      20  53  34.666667  51.0   65.0  59.500000   1.58  1.77  1.676667

     colesterol
            min    max     mean
sexo
H         182.0  280.0  228.375
M         148.0  262.0  207.200

Agregaciones personalizadas por sexo:

/tmp/ipykernel_103905/4140245673.py:13: FutureWarning: The provided callable <function std at 0x7a877f3399e0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  display(df.groupby('sexo').agg({

           edad       peso    altura colesterol
           mean min    max       std      count
sexo
H     40.875000  18  109.0  0.091300          8
M     34.666667  20   65.0  0.070616          5

### Reestructurar un DataFrame
A menudo la disposición de los datos en un DataFrame no es la adecuada para su tratamiento y es
necesario reestructurar el DataFrame. Los datos que contiene un DataFrame pueden organizarse en
dos formatos: ancho y largo.
Formatos de un DataFrame

### Convertir un DataFrame a formato largo
Para convertir un DataFrame de formato ancho a formato largo (columnas a filas) se utiliza el siguiente
método:
• df.melt(id_vars=id-columnas, value_vars=columnas, var_name=nombre-
columnas, var_value=nombre-valores) : Devuelve el DataFrame que resulta de
convertir el DataFrame df de formato ancho a formato largo. Todas las columnas de lista
columnas se reestructuran en dos nuevas columnas con nombres nombre-columnas y
nombre-valores que contienen los nombres de las columnas originales y sus valores, res‑
pectivamente. Las columnas en la lista id-columnas se mantienen sin reestructurar. Si no se
pasa la lista columnas entonces se reestructuran todas las columnas excepto las columnas de
la lista id-columnas.

In [ ]:
datos = {'nombre':['María', 'Luis', 'Carmen'],
         'edad':[18, 22, 20],
         'Matemáticas':[8.5, 7, 3.5],
         'Economía':[8, 6.5, 5],
         'Programación':[6.5, 4, 9]}
df = pd.DataFrame(datos)
df

   nombre  edad  Matemáticas  Economía  Programación
0   María    18          8.5       8.0           6.5
1    Luis    22          7.0       6.5           4.0
2  Carmen    20          3.5       5.0           9.0

In [ ]:
df1 = df.melt(id_vars=['nombre', 'edad'], var_name='asignatura',
value_name='nota')
print(df1)

   nombre  edad    asignatura  nota
0   María    18   Matemáticas   8.5
1    Luis    22   Matemáticas   7.0
2  Carmen    20   Matemáticas   3.5
3   María    18      Economía   8.0
4    Luis    22      Economía   6.5
5  Carmen    20      Economía   5.0
6   María    18  Programación   6.5
7    Luis    22  Programación   4.0
8  Carmen    20  Programación   9.0

### Convertir un DataFrame a formato ancho
Para convertir un DataFrame de formato largo a formato ancho (filas a columnas) se utiliza el siguiente
método:
• df.pivot(index=filas, columns=columna, values=valores) : Devuelve el DataFra‑
me que resulta de convertir el DataFrame df de formato largo a formato ancho. Se crean tantas
columnas nuevas como valores distintos haya en la columna columna. Los nombres de estas
nuevas columnas son los valores de la columna columna mientras que sus valores se toman de la columna valores. Los nombres del índice del nuevo DataFrame se toman de los valores de
la columna filas.

In [ ]:
print(df1.pivot(index='nombre', columns='asignatura', values='nota'))

asignatura  Economía  Matemáticas  Programación
nombre
Carmen           5.0          3.5           9.0
Luis             6.5          7.0           4.0
María            8.0          8.5           6.5

### Exportar resultados

Una vez que hayas procesado tus datos y obtenido los resultados deseados en un DataFrame, a menudo querrás guardarlos en un archivo para su uso posterior o para compartir. pandas ofrece métodos sencillos para exportar DataFrames a varios formatos, siendo CSV y Excel los más comunes.

**`df.to_csv(path_or_buf, sep, index)`**: Exporta el DataFrame `df` a un archivo CSV.
* `path_or_buf`: La ruta y nombre del archivo donde se guardará el DataFrame.
* `sep`: El separador de valores (por defecto es coma ',').
* `index`: Un valor booleano que indica si se debe incluir el índice del DataFrame en el archivo (por defecto es `True`).

In [ ]:
# Exportar el DataFrame 'df' a un archivo CSV
# Se excluye el índice del DataFrame en el archivo CSV.
df.to_csv('colesteroles_procesado.csv', index=False, sep=';')

print("DataFrame 'df' exportado a 'colesteroles_procesado.csv'")

# verificación
df_exported = pd.read_csv('colesteroles_procesado.csv', sep=';')
print("\nPrimeras 5 filas del DataFrame exportado:")
display(df_exported.head())

DataFrame 'df' exportado a 'colesteroles_procesado.csv'

Primeras 5 filas del DataFrame exportado:

                         nombre  edad sexo  peso  altura  colesterol
0  José Luis Martínez Izquierdo    18    H  85.0    1.79       182.0
1                Rosa Díaz Díaz    32    M  65.0    1.73       232.0
2         Javier García Sánchez    24    H   NaN    1.81       191.0
3           Carmen López Pinzón    35    M  65.0    1.70       200.0
4          Marisa López Collado    46    M  51.0    1.58       148.0